In [15]:
# 🚀 CareerPilot X — Colab Library Setup

!pip -q install \
    serpapi \
    gradio \
    pandas==2.2.3 \
    "numpy>=1.24,<2.3" \
    requests==2.32.4 \
    pypdf \
    scikit-learn

print("✅ CareerPilot X libraries installed successfully!")
print("🔄 If Colab asks for a runtime restart, restart it.")

✅ CareerPilot X libraries installed successfully!
🔄 If Colab asks for a runtime restart, restart it.

In [16]:
# 🚀 CareerPilot X — Library Check

import serpapi
import gradio as gr
import pandas as pd
import numpy as np
import requests
import pypdf

print("✅ serpapi:", serpapi.__version__ if hasattr(serpapi, "__version__") else "installed")
print("✅ gradio:", gr.__version__)
print("✅ pandas:", pd.__version__)
print("✅ numpy:", np.__version__)
print("✅ requests:", requests.__version__)
print("✅ pypdf: installed")

print("\n🎉 All CareerPilot X libraries are ready!")

✅ serpapi: 1.1.2
✅ gradio: 6.29.1
✅ pandas: 2.2.3
✅ numpy: 2.1.3
✅ requests: 2.32.4
✅ pypdf: installed

🎉 All CareerPilot X libraries are ready!

In [17]:
# 🔐 CareerPilot X — Secure SerpApi Connection

from google.colab import userdata
import serpapi

SERPAPI_KEY = userdata.get("SERPAPI_KEY")

if not SERPAPI_KEY:
    raise ValueError("❌ SERPAPI_KEY not found. Check Colab Secrets.")

client = serpapi.Client(api_key=SERPAPI_KEY)

print("✅ SerpApi key loaded securely!")
print("🔗 SerpApi client connected!")

✅ SerpApi key loaded securely!
🔗 SerpApi client connected!

In [18]:
# 🔎 CareerPilot X — Live Search Test

test_results = client.search({
    "engine": "google",
    "q": "AI ML internships for freshers India 2026"
})

organic_results = test_results.get("organic_results", [])

print("✅ Live SerpApi search completed!")
print(f"📊 Results received: {len(organic_results)}")

for i, result in enumerate(organic_results[:5], 1):
    print(f"\n{i}. {result.get('title', 'No title')}")
    print(f"   {result.get('link', '')}")

✅ Live SerpApi search completed!
📊 Results received: 9

1. AI Engineer Internship Remote Hiring | LLM + RAG Intern 2026
   https://www.youtube.com/watch?v=03b7Kne2EiI

2. Machine Learning Internships in India (334 open now!)
   https://in.prosple.com/machine-learning-internships-india

3. Internship work from home for machine learning jobs
   https://in.indeed.com/q-internship-work-from-home-for-machine-learning-jobs.html

4. Ai Intern Jobs
   https://www.naukri.com/ai-intern-jobs

5. What are some current paid internship opportunities ...
   https://www.quora.com/What-are-some-current-paid-internship-opportunities-related-to-AI-ML-in-India-that-can-be-done-remotely

In [20]:
# 🎯 CareerPilot X — Smart Opportunity Filter

BLOCKED_DOMAINS = [
    "instagram.com",
    "facebook.com",
    "reddit.com",
    "wikipedia.org",
    "youtube.com",
    "tiktok.com",
    "x.com",
    "twitter.com",
    "researchgate.net",
    "arxiv.org",
    "ieee.org",
    "springer.com",
    "medium.com"
]

STRONG_JOB_TERMS = [
    "internship",
    "intern",
    "job",
    "jobs",
    "hiring",
    "vacancy",
    "opening",
    "career",
    "apply",
    "recruitment",
    "trainee"
]

AI_TERMS = [
    "ai",
    "artificial intelligence",
    "machine learning",
    "ml",
    "deep learning",
    "nlp",
    "natural language processing",
    "generative ai",
    "data science",
    "computer vision",
    "llm"
]


def relevance_score(title, snippet, link, goal, location, experience):

    title = normalize(title)
    snippet = normalize(snippet)
    link = normalize(link)

    text = f"{title} {snippet}"

    # 🚫 Block social/media/academic sources
    for domain in BLOCKED_DOMAINS:
        if domain in link:
            return 0

    score = 20

    goal_text = normalize(goal)

    # 🎯 Career-goal matching
    goal_words = [
        word for word in goal_text.split()
        if len(word) >= 3
    ]

    for word in goal_words:
        if word in text:
            score += 10

    # 🤖 AI/ML relevance
    ai_hits = sum(
        1 for term in AI_TERMS
        if term in text
    )

    score += min(ai_hits * 8, 32)

    # 💼 Actual opportunity signal
    job_hits = sum(
        1 for term in STRONG_JOB_TERMS
        if term in text
    )

    score += min(job_hits * 7, 28)

    # 🇮🇳 Location
    location_text = normalize(location)

    if location_text and location_text in text:
        score += 10

    # 🎓 Fresher/student signal
    if (
        "student" in normalize(experience)
        or "fresher" in normalize(experience)
    ):
        fresher_terms = [
            "fresher",
            "freshers",
            "entry level",
            "graduate",
            "trainee",
            "intern"
        ]

        if any(term in text for term in fresher_terms):
            score += 12

    # ❌ Strongly penalize irrelevant content
    bad_terms = [
        "conference",
        "journal",
        "research paper",
        "webinar",
        "summit",
        "tutorial",
        "course",
        "admission",
        "exam",
        "event"
    ]

    for term in bad_terms:
        if term in text:
            score -= 20

    return safe_score(score)


print("✅ Smart Opportunity Filter installed!")
print("🚫 Social/media/academic noise blocked.")
print("🎯 AI/ML career relevance strengthened.")
print("💼 Job/internship signals strengthened.")

✅ Smart Opportunity Filter installed!
🚫 Social/media/academic noise blocked.
🎯 AI/ML career relevance strengthened.
💼 Job/internship signals strengthened.

In [24]:
# ============================================================
# 🚀 CAREERPILOT X — REBUILD DASHBOARD WITH SMART FILTER
# ============================================================

import gradio as gr
import pandas as pd

# Create a fresh dashboard
with gr.Blocks(
    title="CareerPilot X"
) as demo:

    gr.Markdown("""
# 🚀 CareerPilot X
### Autonomous Career Intelligence Agent

**Live Search → Smart Filtering → Match → Skill Gaps → Career Action**
""")

    with gr.Tab("🚀 Career Mission"):

        gr.Markdown("## 🎯 Tell CareerPilot what you want")

        with gr.Row():
            goal = gr.Textbox(
                label="Career Goal",
                value="AI/ML internships"
            )

            education = gr.Textbox(
                label="Education",
                value="BTech CSE-AIML"
            )

        with gr.Row():
            skills = gr.Textbox(
                label="Your Skills",
                value="Python, Java, AI, Machine Learning, NLP"
            )

            location = gr.Textbox(
                label="Location",
                value="India"
            )

        experience = gr.Textbox(
            label="Experience Level",
            value="Student / Fresher"
        )

        run_button = gr.Button(
            "🚀 START CAREER MISSION",
            variant="primary"
        )

        gr.Markdown("### 📡 Live Research Results")

        results_output = gr.Dataframe(
            headers=[
                "#",
                "Opportunity",
                "Source",
                "Relevance %",
                "Match %",
                "Confidence %",
                "Risk",
                "Remote",
                "Paid Signal"
            ],
            interactive=False,
            wrap=True
        )

        mission_summary = gr.Markdown()

        with gr.Row():
            skill_output = gr.Markdown()
            market_output = gr.Markdown()

        with gr.Row():
            roadmap_output = gr.Markdown()
            research_log = gr.Markdown()

        # IMPORTANT:
        # This connects the new dashboard to the current
        # run_career_mission function, which uses the
        # improved relevance_score filter.

        run_button.click(
            fn=run_career_mission,
            inputs=[
                goal,
                education,
                skills,
                location,
                experience
            ],
            outputs=[
                results_output,
                mission_summary,
                skill_output,
                market_output,
                roadmap_output,
                research_log
            ]
        )

    # --------------------------------------------------------
    # RESUME INTELLIGENCE
    # --------------------------------------------------------

    with gr.Tab("📄 Resume Intelligence"):

        resume_file = gr.File(
            label="Upload Resume PDF",
            file_types=[".pdf"],
            type="filepath"
        )

        resume_goal = gr.Textbox(
            label="Target Career",
            value="AI/ML Engineer"
        )

        resume_skills = gr.Textbox(
            label="Your Skills",
            value="Python, Java, Machine Learning, NLP"
        )

        resume_button = gr.Button(
            "🔍 ANALYZE RESUME",
            variant="primary"
        )

        resume_output = gr.Markdown()

        resume_button.click(
            fn=analyze_resume,
            inputs=[
                resume_file,
                resume_goal,
                resume_skills
            ],
            outputs=resume_output
        )

    # --------------------------------------------------------
    # DIGITAL TWIN
    # --------------------------------------------------------

    with gr.Tab("🤖 Career Digital Twin"):

        twin_button = gr.Button(
            "🤖 BUILD MY DIGITAL TWIN",
            variant="primary"
        )

        twin_output = gr.Markdown()

        twin_button.click(
            fn=digital_twin,
            inputs=[
                goal,
                education,
                skills,
                location,
                experience
            ],
            outputs=twin_output
        )

    # --------------------------------------------------------
    # WHAT-IF LAB
    # --------------------------------------------------------

    with gr.Tab("🧪 What-If Career Lab"):

        extra_skill = gr.Textbox(
            label="Skill to simulate",
            placeholder="Example: TensorFlow"
        )

        whatif_button = gr.Button(
            "🧪 RUN SIMULATION",
            variant="primary"
        )

        whatif_output = gr.Markdown()

        whatif_button.click(
            fn=what_if_analysis,
            inputs=[
                goal,
                skills,
                extra_skill
            ],
            outputs=whatif_output
        )

    # --------------------------------------------------------
    # INTERVIEW
    # --------------------------------------------------------

    with gr.Tab("🎤 Interview Simulator"):

        interview_button = gr.Button(
            "🎤 GENERATE INTERVIEW QUESTIONS",
            variant="primary"
        )

        interview_output = gr.Markdown()

        interview_button.click(
            fn=interview_questions,
            inputs=[
                goal,
                skills
            ],
            outputs=interview_output
        )

    # --------------------------------------------------------
    # COMPARISON
    # --------------------------------------------------------

    with gr.Tab("⚔️ Compare Opportunities"):

        gr.Markdown(
            "Run Career Mission first, then compare opportunity numbers."
        )

        with gr.Row():

            compare_a = gr.Number(
                label="Opportunity #1",
                value=1,
                precision=0
            )

            compare_b = gr.Number(
                label="Opportunity #2",
                value=2,
                precision=0
            )

        compare_button = gr.Button(
            "⚔️ COMPARE",
            variant="primary"
        )

        comparison_output = gr.Markdown()

        compare_button.click(
            fn=compare_opportunities,
            inputs=[
                compare_a,
                compare_b
            ],
            outputs=comparison_output
        )

    # --------------------------------------------------------
    # APPLICATION TRACKER
    # --------------------------------------------------------

    with gr.Tab("📋 Application Tracker"):

        tracker_opportunity = gr.Textbox(
            label="Opportunity"
        )

        tracker_status = gr.Dropdown(
            label="Status",
            choices=[
                "Interested",
                "Applied",
                "Interview",
                "Selected",
                "Rejected"
            ],
            value="Interested"
        )

        tracker_notes = gr.Textbox(
            label="Notes"
        )

        tracker_button = gr.Button(
            "➕ ADD APPLICATION",
            variant="primary"
        )

        tracker_output = gr.Markdown()

        tracker_button.click(
            fn=add_application,
            inputs=[
                tracker_opportunity,
                tracker_status,
                tracker_notes
            ],
            outputs=tracker_output
        )

    gr.Markdown("""
---
### 🏆 SerpApi India Hackathon 2026

**Core:** SerpApi Live Search + Python + Gradio

**Workflow:** Understand → Search → Filter → Match → Reason → Recommend

⚠️ Always verify opportunity details on the original source before applying.
""")


print("✅ Smart-filtered dashboard created!")
print("🎯 Career Mission is connected to the improved filter.")
print("🚀 Launching CareerPilot X...")

demo.launch(
    share=True,
    show_error=True
)

✅ Smart-filtered dashboard created!
🎯 Career Mission is connected to the improved filter.
🚀 Launching CareerPilot X...
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://a6715bd0d0c36d7348.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [25]:
# 🎯 CareerPilot X — Strict Opportunity Filter

BLOCKED_DOMAINS = [
    "instagram.com",
    "facebook.com",
    "reddit.com",
    "wikipedia.org",
    "youtube.com",
    "tiktok.com",
    "twitter.com",
    "x.com",
    "researchgate.net",
    "arxiv.org",
    "ieee.org",
    "springer.com",
    "medium.com"
]

PROFILE_SIGNALS = [
    "profile",
    "people search",
    "pre-final year student",
    "final year student",
    "my profile",
    "about me",
    "student portfolio",
    "personal website"
]

JOB_SIGNALS = [
    "internship",
    "intern",
    "job",
    "jobs",
    "hiring",
    "vacancy",
    "opening",
    "career",
    "apply now",
    "apply",
    "recruitment",
    "trainee",
    "position"
]

AI_SIGNALS = [
    "artificial intelligence",
    "machine learning",
    "ai/ml",
    "ai engineer",
    "ml engineer",
    "deep learning",
    "nlp",
    "natural language processing",
    "generative ai",
    "data science",
    "computer vision",
    "llm",
    "rag"
]


def relevance_score(title, snippet, link, goal, location, experience):

    title = normalize(title)
    snippet = normalize(snippet)
    link = normalize(link)

    text = f"{title} {snippet}"

    # 🚫 Block unwanted domains
    for domain in BLOCKED_DOMAINS:
        if domain in link:
            return 0

    # 🚫 Block personal/profile pages
    profile_hits = sum(
        1 for term in PROFILE_SIGNALS
        if term in text
    )

    if profile_hits >= 1:
        return 0

    score = 15

    # 🎯 Goal matching
    goal_words = [
        word for word in normalize(goal).split()
        if len(word) >= 3
    ]

    for word in goal_words:
        if word in text:
            score += 8

    # 🤖 AI/ML relevance
    ai_hits = sum(
        1 for term in AI_SIGNALS
        if term in text
    )

    score += min(ai_hits * 8, 35)

    # 💼 Real opportunity signals
    job_hits = sum(
        1 for term in JOB_SIGNALS
        if term in text
    )

    score += min(job_hits * 8, 35)

    # 🇮🇳 Location
    location_text = normalize(location)

    if location_text and location_text in text:
        score += 10

    # 🎓 Fresher/student relevance
    experience_text = normalize(experience)

    if "student" in experience_text or "fresher" in experience_text:

        fresher_terms = [
            "fresher",
            "freshers",
            "entry level",
            "graduate",
            "trainee",
            "intern",
            "internship"
        ]

        if any(term in text for term in fresher_terms):
            score += 12

    # 🚫 Academic / informational content
    bad_terms = [
        "research paper",
        "conference",
        "journal",
        "webinar",
        "summit",
        "tutorial",
        "course",
        "admission",
        "exam",
        "event",
        "how to learn"
    ]

    for term in bad_terms:
        if term in text:
            score -= 25

    return safe_score(score)


print("✅ Strict Opportunity Filter installed!")
print("🚫 Personal profiles blocked")
print("🚫 Social/research pages blocked")
print("🎯 Actual job/internship signals prioritized")

✅ Strict Opportunity Filter installed!
🚫 Personal profiles blocked
🚫 Social/research pages blocked
🎯 Actual job/internship signals prioritized

In [31]:
# ============================================================
# 🔧 FINAL RELEVANCE FILTER FIX
# ============================================================

def relevance_score(title, snippet, link, goal, *extra_args):

    title = str(title or "").lower()
    snippet = str(snippet or "").lower()
    link = str(link or "").lower()
    goal = str(goal or "").lower()

    text = f"{title} {snippet}"

    # Block unwanted websites
    blocked_domains = [
        "instagram.com",
        "facebook.com",
        "reddit.com",
        "wikipedia.org",
        "youtube.com",
        "tiktok.com",
        "x.com",
        "twitter.com",
        "researchgate.net",
        "arxiv.org",
        "ieee.org",
        "springer.com",
        "medium.com"
    ]

    if any(domain in link for domain in blocked_domains):
        return 0

    # Block personal LinkedIn profiles
    if "linkedin.com/in/" in link:
        return 0

    if "linkedin.com/pub/" in link:
        return 0

    # Block personal/student pages
    profile_signals = [
        "profile of",
        "my profile",
        "student portfolio",
        "personal website",
        "about me",
        "resume of",
        "cv of",
        "pre-final year student",
        "final year student",
        "student profile",
        "portfolio of"
    ]

    if any(signal in text for signal in profile_signals):
        return 0

    # Block profile-style titles
    profile_patterns = [
        r"\bpre-final year\b",
        r"\bfinal year student\b",
        r"\bstudent at\b",
        r"\bprofile of\b",
        r"\bresume of\b",
        r"\bcv of\b",
        r"\babout me\b"
    ]

    if any(re.search(pattern, title) for pattern in profile_patterns):
        return 0

    # Actual job/internship signals
    job_signals = [
        "job",
        "jobs",
        "intern",
        "internship",
        "hiring",
        "vacancy",
        "vacancies",
        "career",
        "careers",
        "apply",
        "employment",
        "opening",
        "openings",
        "recruitment",
        "recruiting",
        "trainee",
        "fresher",
        "graduate role"
    ]

    if not any(signal in text for signal in job_signals):
        return 0

    # AI/ML signals
    ai_signals = [
        "artificial intelligence",
        "machine learning",
        "ai/ml",
        "ai engineer",
        "ml engineer",
        "data science",
        "deep learning",
        "nlp",
        "natural language processing",
        "generative ai",
        "genai",
        "computer vision",
        "llm",
        "large language model",
        "rag"
    ]

    ai_goal = any(
        word in goal
        for word in [
            "ai",
            "ml",
            "machine learning",
            "artificial intelligence",
            "data science",
            "nlp",
            "deep learning"
        ]
    )

    if ai_goal and not any(
        signal in text for signal in ai_signals
    ):
        return 0

    # Calculate relevance
    score = 35

    ai_hits = sum(
        1 for signal in ai_signals
        if signal in text
    )

    score += min(ai_hits * 8, 32)

    job_hits = sum(
        1 for signal in job_signals
        if signal in text
    )

    score += min(job_hits * 4, 16)

    goal_words = [
        word
        for word in re.findall(r"[a-zA-Z]+", goal)
        if len(word) > 2
    ]

    goal_hits = sum(
        1 for word in goal_words
        if word in text
    )

    score += min(goal_hits * 3, 12)

    return min(score, 100)


print("✅ FINAL relevance_score loaded")
print("✅ Accepts the existing 6 arguments")
print("✅ Profile filtering enabled")
print("✅ Job filtering enabled")

✅ FINAL relevance_score loaded
✅ Accepts the existing 6 arguments
✅ Profile filtering enabled
✅ Job filtering enabled

In [32]:
import traceback

try:
    result = run_career_mission(
        "AI/ML internships",
        "BTech CSE-AIML",
        "Python, Java, AI, Machine Learning, NLP",
        "India",
        "Student"
    )

    print("🎉 SUCCESS!")
    print("Career mission completed.")
    print(result)

except Exception:
    print("❌ ERROR:")
    traceback.print_exc()

🎉 SUCCESS!
Career mission completed.
(   #                                        Opportunity           Source  \
0  1  170 internship fresher jobs in Ahmedabad, July...  glassdoor.co.in
1  2  585 internship as data engineer jobs in India,...  glassdoor.co.in
2  3         Ai Internships jobs in Chennai, Tamil Nadu    in.indeed.com
3  4        Machine Learning Internships for AI Careers     linkedin.com
4  5  13 Subject Matter Expert Sme Ai Ml Jobs for Fr...  internshala.com
5  6            Careers & AI Internships - 3A Tech Mind   3atechmind.com
6  7  Shanmukha sai Bontha | Find professionals and ...        bebee.com
7  8  Can AI skills help students get internships in...        quora.com
8  9  AI and ML Internships Summer 2027: Companies &...       extern.com

   Relevance %  Match %  Confidence %          Risk           Remote  \
0           86     74.0          63.0  🟢 Low signal  On-site/Unknown
1           86     74.0          63.0  🟢 Low signal  On-site/Unknown
2           70     61.0          93.0  🟢 Low signal  On-site/Unknown
3           70     61.0          93.0  🟢 Low signal  On-site/Unknown
4           70     61.0          93.0  🟢 Low signal  On-site/Unknown
5           62     48.0          63.0  🟢 Low signal  On-site/Unknown
6           62     48.0          63.0  🟢 Low signal  On-site/Unknown
7           58     48.0          63.0  🟢 Low signal  On-site/Unknown
8           58     48.0          63.0  🟢 Low signal  On-site/Unknown

     Paid Signal
0     Not stated
1     Not stated
2     Not stated
3  💰 Paid signal
4     Not stated
5  💰 Paid signal
6     Not stated
7     Not stated
8     Not stated  , '\n## 🚀 Career Mission Complete\n\n**Target:** AI/ML internships\n\n**Opportunities found:** 9\n\n**Top opportunity:** 170 internship fresher jobs in Ahmedabad, July 2026\n\n**Top relevance:** 86%\n\n**Top match:** 74.0%\n\n### 🧠 Agent workflow\n\nUnderstand → Plan Search → Live Search → Filter → Verify Signals → Match → Rank → Recommend\n', '## 🛠️ Skill Intelligence\n\n**Market-matched skills:**\n- ✅ Ai\n- ✅ Machine Learning\n- ✅ Nlp\n\n**Potential skill gaps:**\n- 📚 Artificial Intelligence\n- 📚 Generative Ai\n- 📚 Rag', '## 📈 Live Market Intelligence\n\n- **Ai** — 26 signal(s)\n- **Machine Learning** — 5 signal(s)\n- **Generative Ai** — 3 signal(s)\n- **Nlp** — 2 signal(s)\n- **Artificial Intelligence** — 1 signal(s)\n- **Rag** — 1 signal(s)\n', '🎯 Target: AI/ML internships\n1️⃣ Strengthen programming fundamentals\n2️⃣ Learn and practice: Artificial Intelligence\n3️⃣ Learn and practice: Generative Ai\n4️⃣ Learn and practice: Rag\n7️⃣ Build 2–3 portfolio projects\n8️⃣ Publish projects on GitHub\n9️⃣ Prepare resume and LinkedIn\n🔟 Apply consistently and track applications', '🧠 Understanding career objective...\n🔎 Search strategy created: 2 queries\n🌐 Searching live web: "AI/ML internships" India Student jobs internships\n🌐 Searching live web: "AI/ML internships" India fresher careers Python, Java, AI, Machine Learning, NLP\n🔍 Raw relevant opportunities collected: 9\n🎯 Final shortlist: 9 opportunities\n✅ Research and ranking completed.')

In [34]:
# ============================================================
# 🔧 GRADIO OUTPUT FIX
# ============================================================

import gradio as gr
import pandas as pd
import traceback


def safe_career_mission(
    goal,
    education,
    skills,
    location,
    experience
):
    try:

        result = run_career_mission(
            goal,
            education,
            skills,
            location,
            experience
        )

        # Make sure we received the expected result
        if not isinstance(result, tuple):
            raise ValueError(
                f"Career Mission returned {type(result)} instead of a tuple."
            )

        if len(result) != 10:
            raise ValueError(
                f"Career Mission returned {len(result)} outputs instead of 10."
            )

        (
            status,
            count,
            top_opportunity,
            top_relevance,
            top_match,
            opportunities,
            market,
            skill_gap,
            roadmap,
            research_log
        ) = result

        # Convert dataframe into Gradio-safe data
        if isinstance(opportunities, pd.DataFrame):

            opportunities = opportunities.copy()

            opportunities = opportunities.fillna("")

            # Convert everything to normal Python values
            opportunities = opportunities.astype(str)

            opportunities = opportunities.values.tolist()

        elif opportunities is None:

            opportunities = []

        else:

            try:
                opportunities = pd.DataFrame(
                    opportunities
                ).fillna("").astype(str).values.tolist()

            except Exception:
                opportunities = []

        # Safe numbers
        try:
            count = int(count or 0)
        except:
            count = 0

        try:
            top_relevance = float(top_relevance or 0)
        except:
            top_relevance = 0

        try:
            top_match = float(top_match or 0)
        except:
            top_match = 0

        # Safe text values
        status = str(status or "")
        top_opportunity = str(top_opportunity or "")
        market = str(market or "")
        skill_gap = str(skill_gap or "")
        roadmap = str(roadmap or "")
        research_log = str(research_log or "")

        print("✅ Gradio-safe Career Mission completed")

        return (
            status,
            count,
            top_opportunity,
            top_relevance,
            top_match,
            opportunities,
            market,
            skill_gap,
            roadmap,
            research_log
        )

    except Exception as e:

        print("❌ Career Mission error:")
        traceback.print_exc()

        error_message = (
            "### ❌ Career Mission Error\n\n"
            f"`{type(e).__name__}: {str(e)}`"
        )

        return (
            error_message,
            0,
            "Error",
            0,
            0,
            [],
            error_message,
            error_message,
            error_message,
            error_message
        )


print("✅ Safe Gradio wrapper created")

✅ Safe Gradio wrapper created

In [36]:
def safe_career_mission(goal, education, skills, location, experience):
    try:
        result = run_career_mission(
            goal,
            education,
            skills,
            location,
            experience
        )

        print("✅ Original function returned:", len(result), "outputs")

        # Show what each output contains
        for i, item in enumerate(result):
            print(f"\n--- OUTPUT {i+1} ---")
            print(type(item))
            print(str(item)[:500])

        # Return exactly what the original function returns
        return result

    except Exception as e:
        import traceback
        print("❌ Career Mission error:")
        traceback.print_exc()
        return (
            f"Error: {type(e).__name__}: {str(e)}",
            0,
            "Error",
            0,
            0,
            []
        )

print("✅ Corrected safe wrapper created")

✅ Corrected safe wrapper created

In [37]:
test = safe_career_mission(
    "AI/ML internships",
    "BTech CSE-AIML",
    "Python, Java, AI, Machine Learning, NLP",
    "India",
    "Student"
)

✅ Original function returned: 6 outputs

--- OUTPUT 1 ---
<class 'pandas.core.frame.DataFrame'>
   #                                        Opportunity           Source  \
0  1  170 internship fresher jobs in Ahmedabad, July...  glassdoor.co.in
1  2  585 internship as data engineer jobs in India,...  glassdoor.co.in
2  3         Ai Internships jobs in Chennai, Tamil Nadu    in.indeed.com
3  4        Machine Learning Internships for AI Careers     linkedin.com
4  5  13 Subject Matter Expert Sme Ai Ml Jobs for Fr...  internshala.com
5  6            Careers & AI Internships - 3

--- OUTPUT 2 ---
<class 'str'>

## 🚀 Career Mission Complete

**Target:** AI/ML internships

**Opportunities found:** 9

**Top opportunity:** 170 internship fresher jobs in Ahmedabad, July 2026

**Top relevance:** 86%

**Top match:** 74.0%

### 🧠 Agent workflow

Understand → Plan Search → Live Search → Filter → Verify Signals → Match → Rank → Recommend


--- OUTPUT 3 ---
<class 'str'>
## 🛠️ Skill Intelligence

**Market-matched skills:**
- ✅ Ai
- ✅ Machine Learning
- ✅ Nlp

**Potential skill gaps:**
- 📚 Artificial Intelligence
- 📚 Generative Ai
- 📚 Rag

--- OUTPUT 4 ---
<class 'str'>
## 📈 Live Market Intelligence

- **Ai** — 26 signal(s)
- **Machine Learning** — 5 signal(s)
- **Generative Ai** — 3 signal(s)
- **Nlp** — 2 signal(s)
- **Artificial Intelligence** — 1 signal(s)
- **Rag** — 1 signal(s)


--- OUTPUT 5 ---
<class 'str'>
🎯 Target: AI/ML internships
1️⃣ Strengthen programming fundamentals
2️⃣ Learn and practice: Artificial Intelligence
3️⃣ Learn and practice: Generative Ai
4️⃣ Learn and practice: Rag
7️⃣ Build 2–3 portfolio projects
8️⃣ Publish projects on GitHub
9️⃣ Prepare resume and LinkedIn
🔟 Apply consistently and track applications

--- OUTPUT 6 ---
<class 'str'>
🧠 Understanding career objective...
🔎 Search strategy created: 2 queries
🌐 Searching live web: "AI/ML internships" India Student jobs internships
🌐 Searching live web: "AI/ML internships" India fresher careers Python, Java, AI, Machine Learning, NLP
🔍 Raw relevant opportunities collected: 9
🎯 Final shortlist: 9 opportunities
✅ Research and ranking completed.

In [39]:
# ============================================================
# 📄 CAREERPILOT X — RESUME INTELLIGENCE ENGINE
# ============================================================

import re
import os
import pandas as pd

# Common career skills we can detect
CAREER_SKILLS = [
    "python", "java", "c++", "c", "sql", "javascript",
    "html", "css", "react", "node.js", "git", "github",
    "machine learning", "deep learning", "artificial intelligence",
    "ai", "ml", "nlp", "tensorflow", "pytorch",
    "pandas", "numpy", "scikit-learn", "opencv",
    "generative ai", "genai", "rag", "langchain",
    "llm", "data science", "data analysis",
    "power bi", "tableau", "aws", "azure", "gcp",
    "docker", "kubernetes", "linux", "flask", "django",
    "fastapi", "mongodb", "mysql", "postgresql"
]


def extract_resume_text(file_path):
    """Extract text from PDF or TXT resume."""

    if not file_path:
        return ""

    # Gradio may provide a filepath string
    if hasattr(file_path, "name"):
        file_path = file_path.name

    file_path = str(file_path)

    try:

        # PDF
        if file_path.lower().endswith(".pdf"):

            from pypdf import PdfReader

            reader = PdfReader(file_path)

            pages = []

            for page in reader.pages:
                text = page.extract_text() or ""
                pages.append(text)

            return "\n".join(pages)

        # TXT
        elif file_path.lower().endswith(".txt"):

            with open(
                file_path,
                "r",
                encoding="utf-8",
                errors="ignore"
            ) as f:
                return f.read()

        return ""

    except Exception as e:

        print("Resume extraction error:", e)

        return ""


def extract_resume_skills(text):

    text_lower = text.lower()

    found = []

    for skill in CAREER_SKILLS:

        pattern = r"(?<!\w)" + re.escape(skill.lower()) + r"(?!\w)"

        if re.search(pattern, text_lower):

            found.append(skill)

    return sorted(set(found))


def resume_intelligence(resume_file, opportunities=None):

    text = extract_resume_text(resume_file)

    if not text.strip():

        return (
            "❌ Could not extract text from the resume.",
            [],
            0,
            [],
            "Please upload a text-based PDF or TXT resume."
        )

    skills = extract_resume_skills(text)

    # --------------------------------------------------------
    # Compare resume skills with live opportunities
    # --------------------------------------------------------

    matched_skills = set()
    missing_skills = set()

    opportunity_results = []

    if opportunities is not None:

        if isinstance(opportunities, pd.DataFrame):

            df = opportunities.copy()

        else:

            try:
                df = pd.DataFrame(opportunities)
            except:
                df = pd.DataFrame()

        if not df.empty:

            for _, row in df.iterrows():

                title = str(
                    row.get("Opportunity", "")
                )

                combined = title.lower()

                job_skills = []

                for skill in CAREER_SKILLS:

                    if skill.lower() in combined:

                        job_skills.append(skill)

                job_skill_set = set(job_skills)

                matched = job_skill_set.intersection(skills)

                missing = job_skill_set.difference(skills)

                matched_skills.update(matched)

                missing_skills.update(missing)

                score = 0

                if job_skill_set:

                    score = round(
                        len(matched) /
                        len(job_skill_set) * 100,
                        1
                    )

                else:

                    score = 50

                opportunity_results.append({
                    "Opportunity": title,
                    "Resume Match %": score,
                    "Matched Skills": ", ".join(
                        sorted(matched)
                    ),
                    "Potential Gaps": ", ".join(
                        sorted(missing)
                    )
                })

    # --------------------------------------------------------
    # Overall resume score
    # --------------------------------------------------------

    if opportunity_results:

        overall_score = round(
            sum(
                x["Resume Match %"]
                for x in opportunity_results
            ) / len(opportunity_results),
            1
        )

    else:

        overall_score = 0

    # --------------------------------------------------------
    # Recommendations
    # --------------------------------------------------------

    recommendations = []

    for skill in sorted(missing_skills):

        recommendations.append(
            f"📚 Learn or strengthen **{skill.title()}**"
        )

    if not recommendations:

        recommendations.append(
            "🎉 No major skill gaps detected from the current opportunities."
        )

    summary = f"""
## 📄 Resume Intelligence

### 🎯 Overall Resume Match
**{overall_score}%**

### 💻 Skills Detected
{", ".join(s.title() for s in skills) if skills else "No recognised technical skills detected."}

### ✅ Market-Matched Skills
{", ".join(s.title() for s in sorted(matched_skills)) if matched_skills else "No direct matches yet."}

### 📚 Potential Skill Gaps
{", ".join(s.title() for s in sorted(missing_skills)) if missing_skills else "No major gaps detected."}
"""

    return (
        summary,
        sorted(skills),
        overall_score,
        opportunity_results,
        "\n".join(recommendations)
    )


print("✅ Resume Intelligence Engine created successfully!")

✅ Resume Intelligence Engine created successfully!

In [43]:
# ============================================================
# 🎯 CAREERPILOT X — OPPORTUNITY INTELLIGENCE ENGINE
# ============================================================

import pandas as pd
import re


def opportunity_intelligence(opportunities, user_skills=""):
    """
    Analyze live opportunities and rank the strongest choices.
    """

    if opportunities is None:
        return (
            "❌ No opportunities available.",
            pd.DataFrame()
        )

    if not isinstance(opportunities, pd.DataFrame):
        try:
            opportunities = pd.DataFrame(opportunities)
        except:
            return (
                "❌ Could not process opportunities.",
                pd.DataFrame()
            )

    if opportunities.empty:
        return (
            "❌ No opportunities found. Run Career Mission first.",
            pd.DataFrame()
        )

    user_skill_list = [
        x.strip().lower()
        for x in str(user_skills).split(",")
        if x.strip()
    ]

    results = []

    for _, row in opportunities.iterrows():

        title = str(
            row.get("Opportunity", "")
        )

        source = str(
            row.get("Source", "")
        )

        text = f"{title} {source}".lower()

        # ----------------------------------------------------
        # Extract recognizable skills
        # ----------------------------------------------------

        detected_skills = []

        for skill in CAREER_SKILLS:

            if skill.lower() in text:

                detected_skills.append(skill)

        detected_set = set(
            x.lower()
            for x in detected_skills
        )

        user_set = set(user_skill_list)

        matched = detected_set.intersection(user_set)

        missing = detected_set.difference(user_set)

        # ----------------------------------------------------
        # Existing scores
        # ----------------------------------------------------

        try:
            relevance = float(
                row.get("Relevance %", 0)
            )
        except:
            relevance = 0

        try:
            match = float(
                row.get("Match %", 0)
            )
        except:
            match = 0

        # ----------------------------------------------------
        # Skill alignment
        # ----------------------------------------------------

        if detected_set:

            skill_alignment = round(
                len(matched) /
                len(detected_set) * 100,
                1
            )

        else:

            skill_alignment = 50

        # ----------------------------------------------------
        # Remote / paid signals
        # ----------------------------------------------------

        remote = "Unknown"

        if any(
            x in text
            for x in [
                "remote",
                "work from home",
                "wfh"
            ]
        ):
            remote = "Likely Remote"

        elif "onsite" in text or "on-site" in text:
            remote = "Likely On-site"

        paid = "Unknown"

        if any(
            x in text
            for x in [
                "paid internship",
                "stipend",
                "salary",
                "₹",
                "inr"
            ]
        ):
            paid = "Potentially Paid"

        # ----------------------------------------------------
        # Overall opportunity score
        # ----------------------------------------------------

        overall = round(
            (
                relevance * 0.35
                + match * 0.35
                + skill_alignment * 0.30
            ),
            1
        )

        # ----------------------------------------------------
        # Priority
        # ----------------------------------------------------

        if overall >= 80:
            priority = "🔥 HIGH"

        elif overall >= 65:
            priority = "🟡 MEDIUM"

        else:
            priority = "⚪ LOW"

        results.append({
            "Opportunity": title,
            "Source": source,
            "Overall Score": overall,
            "Relevance": relevance,
            "Match": match,
            "Skill Alignment": skill_alignment,
            "Matched Skills": ", ".join(
                sorted(matched)
            ),
            "Potential Gaps": ", ".join(
                sorted(missing)
            ),
            "Remote Signal": remote,
            "Paid Signal": paid,
            "Priority": priority
        })

    result_df = pd.DataFrame(results)

    result_df = result_df.sort_values(
        "Overall Score",
        ascending=False
    ).reset_index(drop=True)

    # --------------------------------------------------------
    # Best opportunity
    # --------------------------------------------------------

    best = result_df.iloc[0]

    summary = f"""
## 🏆 Opportunity Intelligence

### 🎯 Best Opportunity

**{best["Opportunity"]}**

### ⭐ CareerPilot Score
**{best["Overall Score"]}%**

### 🔎 Relevance
**{best["Relevance"]}%**

### 🧠 Profile Match
**{best["Match"]}%**

### 💻 Skill Alignment
**{best["Skill Alignment"]}%**

### 🌐 Remote Signal
**{best["Remote Signal"]}**

### 💰 Payment Signal
**{best["Paid Signal"]}**

### ⚡ Priority
**{best["Priority"]}**

### ✅ Matched Skills

{best["Matched Skills"] or "No direct skill matches detected."}

### 📚 Potential Skill Gaps

{best["Potential Gaps"] or "No major gaps detected."}

---

### 🧠 Why CareerPilot recommends it

CareerPilot combines:

**Relevance + Profile Match + Skill Alignment**

to rank opportunities instead of simply returning search results.
"""

    return summary, result_df


print("✅ Opportunity Intelligence Engine created!")

✅ Opportunity Intelligence Engine created!

In [40]:
# 🧪 Test Resume Intelligence Engine

print("✅ Resume Intelligence function is ready.")

print("\nExpected workflow:")
print("📄 Upload Resume")
print("   ↓")
print("💻 Extract Skills")
print("   ↓")
print("🎯 Compare with Opportunities")
print("   ↓")
print("📊 Calculate Match")
print("   ↓")
print("📚 Identify Skill Gaps")
print("   ↓")
print("🚀 Recommend Learning")

print("\n✅ Engine test completed successfully!")

✅ Resume Intelligence function is ready.

Expected workflow:
📄 Upload Resume
   ↓
💻 Extract Skills
   ↓
🎯 Compare with Opportunities
   ↓
📊 Calculate Match
   ↓
📚 Identify Skill Gaps
   ↓
🚀 Recommend Learning

✅ Engine test completed successfully!

In [46]:
# ============================================================
# 🤖 CAREERPILOT X — INTERVIEW SIMULATOR ENGINE
# ============================================================

import re
import random


INTERVIEW_QUESTION_BANK = {

    "python": [
        "What is the difference between a list, tuple, set, and dictionary in Python?",
        "What are Python decorators and where would you use them?",
        "Explain exception handling in Python.",
        "What is the difference between == and is in Python?"
    ],

    "machine learning": [
        "What is the difference between supervised and unsupervised learning?",
        "What is overfitting and how can you prevent it?",
        "Explain the difference between classification and regression.",
        "What is cross-validation and why is it useful?"
    ],

    "artificial intelligence": [
        "What is Artificial Intelligence and how is it different from Machine Learning?",
        "What are the major applications of Artificial Intelligence?",
        "What is the difference between narrow AI and general AI?",
        "How would you evaluate an AI system?"
    ],

    "nlp": [
        "What is Natural Language Processing?",
        "What is tokenization in NLP?",
        "What is the difference between stemming and lemmatization?",
        "How would you build a basic text classification system?"
    ],

    "generative ai": [
        "What is Generative AI?",
        "What is an LLM?",
        "What is prompt engineering?",
        "What are hallucinations in Generative AI and how can they be reduced?"
    ],

    "rag": [
        "What is Retrieval-Augmented Generation?",
        "Why is RAG useful for reducing hallucinations?",
        "What are embeddings in a RAG system?",
        "Explain the basic architecture of a RAG application."
    ],

    "sql": [
        "What is the difference between WHERE and HAVING in SQL?",
        "Explain INNER JOIN and LEFT JOIN.",
        "What is database normalization?",
        "How would you find duplicate records in a SQL table?"
    ],

    "java": [
        "What are the main principles of Object-Oriented Programming?",
        "What is the difference between an interface and an abstract class in Java?",
        "Explain inheritance and polymorphism.",
        "What is exception handling in Java?"
    ]
}


def generate_interview_questions(
    career_goal,
    skills,
    number_of_questions=5
):

    skill_text = str(skills).lower()

    selected = []

    # Match questions to user skills
    for skill, questions in INTERVIEW_QUESTION_BANK.items():

        if skill in skill_text or skill in str(career_goal).lower():

            selected.extend(questions)

    # Generic questions if not enough matches
    generic = [
        "Tell me about yourself and your technical background.",
        "Describe an AI or software project you have worked on.",
        "What was the biggest technical challenge in your project?",
        "How do you debug a program when it produces an unexpected result?",
        "Why are you interested in this career?",
        "How do you keep yourself updated with new technologies?"
    ]

    selected.extend(generic)

    # Remove duplicates
    selected = list(dict.fromkeys(selected))

    random.shuffle(selected)

    return selected[:number_of_questions]


def evaluate_interview_answer(question, answer):

    answer = str(answer).strip()

    if not answer:

        return (
            "❌ No answer provided.",
            0,
            "Please provide an answer first."
        )

    words = answer.split()

    word_count = len(words)

    # Basic structured evaluation
    if word_count < 10:

        score = 35
        feedback = (
            "Your answer is too short. "
            "Add an explanation and a practical example."
        )

    elif word_count < 25:

        score = 60
        feedback = (
            "Good start. Improve the answer with "
            "more technical detail and an example."
        )

    elif word_count < 50:

        score = 80
        feedback = (
            "Good answer. You explained the concept "
            "with reasonable detail."
        )

    else:

        score = 90
        feedback = (
            "Strong answer. It contains enough detail. "
            "Try to keep it structured and concise in a real interview."
        )

    # Technical keywords
    technical_terms = [
        "because",
        "example",
        "project",
        "algorithm",
        "model",
        "data",
        "python",
        "machine learning",
        "ai",
        "nlp",
        "training",
        "testing"
    ]

    found_terms = [
        term
        for term in technical_terms
        if term in answer.lower()
    ]

    if len(found_terms) >= 3:
        score = min(100, score + 5)

    result = f"""
## 🤖 Interview Evaluation

### ⭐ Score
**{score}/100**

### 💬 Feedback
{feedback}

### 🧠 Technical signals detected
{", ".join(found_terms) if found_terms else "Add more technical terminology."}

### 📌 Improvement tip
Use this structure:

**Concept → Explanation → Example → Result**
"""

    return result, score, feedback


def interview_session(
    career_goal,
    skills,
    number_of_questions
):

    questions = generate_interview_questions(
        career_goal,
        skills,
        int(number_of_questions)
    )

    formatted = ""

    for i, question in enumerate(
        questions,
        start=1
    ):

        formatted += (
            f"### Question {i}\n"
            f"**{question}**\n\n"
        )

    return formatted


print("✅ Interview Simulator Engine created!")

✅ Interview Simulator Engine created!

In [45]:
import gradio as gr
import pandas as pd

# Keep latest Career Mission opportunities
CAREER_MISSION_CACHE = {
    "opportunities": pd.DataFrame()
}


# ============================================================
# CAREER MISSION
# ============================================================

def career_dashboard_with_cache(
    goal,
    education,
    skills,
    location,
    experience
):
    result = run_career_mission(
        goal,
        education,
        skills,
        location,
        experience
    )

    opportunities = result[0]

    if isinstance(opportunities, pd.DataFrame):
        CAREER_MISSION_CACHE["opportunities"] = opportunities.copy()

    return result


# ============================================================
# RESUME INTELLIGENCE
# ============================================================

def analyze_uploaded_resume(resume_file):

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    return resume_intelligence(
        resume_file,
        opportunities
    )


# ============================================================
# OPPORTUNITY INTELLIGENCE
# ============================================================

def analyze_opportunities(user_skills):

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if opportunities.empty:

        return (
            "❌ No opportunities available.\n\n"
            "Please run **Career Mission** first.",
            pd.DataFrame()
        )

    return opportunity_intelligence(
        opportunities,
        user_skills
    )


# ============================================================
# BUILD CAREERPILOT X
# ============================================================

with gr.Blocks(
    title="CareerPilot X"
) as demo:

    gr.Markdown(
        """
# 🚀 CareerPilot X
### Autonomous Career Intelligence Agent

**Live career intelligence powered by SerpApi**

**Understand → Research → Analyze → Match → Decide → Act**
"""
    )

    # ========================================================
    # TAB 1 — CAREER MISSION
    # ========================================================

    with gr.Tab("🎯 Career Mission"):

        gr.Markdown(
            "## Find and rank live career opportunities"
        )

        with gr.Row():

            with gr.Column():

                goal = gr.Textbox(
                    label="🎯 Career Goal",
                    value="AI/ML internships"
                )

                education = gr.Textbox(
                    label="🎓 Education",
                    value="BTech CSE-AIML"
                )

                skills = gr.Textbox(
                    label="💻 Skills",
                    value="Python, Java, AI, Machine Learning, NLP"
                )

                location = gr.Textbox(
                    label="📍 Location",
                    value="India"
                )

                experience = gr.Textbox(
                    label="👤 Experience",
                    value="Student"
                )

                mission_button = gr.Button(
                    "🚀 Start Career Mission",
                    variant="primary"
                )

        opportunities = gr.Dataframe(
            label="🎯 Ranked Opportunities",
            interactive=False
        )

        mission = gr.Markdown()

        skill_intelligence = gr.Markdown()

        market = gr.Markdown()

        roadmap = gr.Markdown()

        research = gr.Markdown()

        mission_button.click(
            fn=career_dashboard_with_cache,
            inputs=[
                goal,
                education,
                skills,
                location,
                experience
            ],
            outputs=[
                opportunities,
                mission,
                skill_intelligence,
                market,
                roadmap,
                research
            ]
        )

    # ========================================================
    # TAB 2 — RESUME INTELLIGENCE
    # ========================================================

    with gr.Tab("📄 Resume Intelligence"):

        gr.Markdown(
            """
## 📄 Resume → Career Intelligence

Upload your resume and CareerPilot X will:

**Extract Skills → Compare → Calculate Match → Identify Gaps → Recommend Learning**
"""
        )

        resume_file = gr.File(
            label="📄 Upload Resume",
            file_types=[".pdf", ".txt"],
            type="filepath"
        )

        analyze_resume_button = gr.Button(
            "🧠 Analyze My Resume",
            variant="primary"
        )

        resume_summary = gr.Markdown()

        detected_skills = gr.Textbox(
            label="💻 Detected Skills",
            interactive=False
        )

        overall_match = gr.Number(
            label="🎯 Overall Resume Match %",
            interactive=False
        )

        resume_results = gr.Dataframe(
            label="📊 Resume → Opportunity Matching",
            interactive=False
        )

        recommendations = gr.Markdown()

        analyze_resume_button.click(
            fn=analyze_uploaded_resume,
            inputs=resume_file,
            outputs=[
                resume_summary,
                detected_skills,
                overall_match,
                resume_results,
                recommendations
            ]
        )

    # ========================================================
    # TAB 3 — OPPORTUNITY INTELLIGENCE
    # ========================================================

    with gr.Tab("🏆 Opportunity Intelligence"):

        gr.Markdown(
            """
## 🏆 Opportunity Intelligence

CareerPilot X analyzes the live opportunities discovered by
Career Mission and identifies the strongest choices for you.

**Relevance + Profile Match + Skill Alignment → CareerPilot Score**
"""
        )

        user_skills_input = gr.Textbox(
            label="💻 Your Skills",
            value="Python, Java, AI, Machine Learning, NLP",
            placeholder="Python, SQL, Machine Learning..."
        )

        analyze_opportunity_button = gr.Button(
            "🏆 Find My Best Opportunities",
            variant="primary"
        )

        best_opportunity = gr.Markdown()

        opportunity_table = gr.Dataframe(
            label="📊 Ranked Opportunity Intelligence",
            interactive=False
        )

        analyze_opportunity_button.click(
            fn=analyze_opportunities,
            inputs=user_skills_input,
            outputs=[
                best_opportunity,
                opportunity_table
            ]
        )

    # ========================================================
    # FOOTER
    # ========================================================

    gr.Markdown(
        """
---

### 🔄 CareerPilot X

**Discover → Analyze → Match → Decide → Act → Improve**

Built with **Python + Gradio + SerpApi**
"""
    )


demo.launch(
    share=True,
    debug=True
)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://a2d7ecf7ab5a9776eb.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7866 <> https://a2d7ecf7ab5a9776eb.gradio.live

In [48]:
import gradio as gr
import pandas as pd

# Keep latest Career Mission opportunities
CAREER_MISSION_CACHE = {
    "opportunities": pd.DataFrame()
}


# ============================================================
# CAREER MISSION
# ============================================================

def career_dashboard_with_cache(
    goal,
    education,
    skills,
    location,
    experience
):
    result = run_career_mission(
        goal,
        education,
        skills,
        location,
        experience
    )

    opportunities = result[0]

    if isinstance(opportunities, pd.DataFrame):
        CAREER_MISSION_CACHE["opportunities"] = opportunities.copy()

    return result


# ============================================================
# RESUME INTELLIGENCE
# ============================================================

def analyze_uploaded_resume(resume_file):

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    return resume_intelligence(
        resume_file,
        opportunities
    )


# ============================================================
# OPPORTUNITY INTELLIGENCE
# ============================================================

def analyze_opportunities(user_skills):

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if opportunities.empty:

        return (
            "❌ No opportunities available.\n\n"
            "Please run **Career Mission** first.",
            pd.DataFrame()
        )

    return opportunity_intelligence(
        opportunities,
        user_skills
    )


# ============================================================
# INTERVIEW SIMULATOR
# ============================================================

def create_interview(
    career_goal,
    skills,
    number_of_questions
):

    try:

        number_of_questions = int(
            number_of_questions
        )

        number_of_questions = max(
            1,
            min(10, number_of_questions)
        )

        return interview_session(
            career_goal,
            skills,
            number_of_questions
        )

    except Exception as e:

        return (
            f"❌ Could not generate interview: "
            f"{type(e).__name__}: {str(e)}"
        )


def evaluate_answer(
    question,
    answer
):

    try:

        return evaluate_interview_answer(
            question,
            answer
        )

    except Exception as e:

        return (
            f"❌ Evaluation error: {str(e)}",
            0,
            "Please try again."
        )


# ============================================================
# BUILD CAREERPILOT X
# ============================================================

with gr.Blocks(
    title="CareerPilot X"
) as demo:

    gr.Markdown(
        """
# 🚀 CareerPilot X
### Autonomous Career Intelligence Agent

**Live career intelligence powered by SerpApi**

**Understand → Research → Analyze → Match → Decide → Act**
"""
    )


    # ========================================================
    # TAB 1 — CAREER MISSION
    # ========================================================

    with gr.Tab("🎯 Career Mission"):

        gr.Markdown(
            "## Find and rank live career opportunities"
        )

        with gr.Row():

            with gr.Column():

                goal = gr.Textbox(
                    label="🎯 Career Goal",
                    value="AI/ML internships"
                )

                education = gr.Textbox(
                    label="🎓 Education",
                    value="BTech CSE-AIML"
                )

                skills = gr.Textbox(
                    label="💻 Skills",
                    value="Python, Java, AI, Machine Learning, NLP"
                )

                location = gr.Textbox(
                    label="📍 Location",
                    value="India"
                )

                experience = gr.Textbox(
                    label="👤 Experience",
                    value="Student"
                )

                mission_button = gr.Button(
                    "🚀 Start Career Mission",
                    variant="primary"
                )

        opportunities = gr.Dataframe(
            label="🎯 Ranked Opportunities",
            interactive=False
        )

        mission = gr.Markdown()

        skill_intelligence = gr.Markdown()

        market = gr.Markdown()

        roadmap = gr.Markdown()

        research = gr.Markdown()

        mission_button.click(
            fn=career_dashboard_with_cache,
            inputs=[
                goal,
                education,
                skills,
                location,
                experience
            ],
            outputs=[
                opportunities,
                mission,
                skill_intelligence,
                market,
                roadmap,
                research
            ]
        )


    # ========================================================
    # TAB 2 — RESUME INTELLIGENCE
    # ========================================================

    with gr.Tab("📄 Resume Intelligence"):

        gr.Markdown(
            """
## 📄 Resume → Career Intelligence

**Extract Skills → Compare → Calculate Match → Identify Gaps → Recommend Learning**
"""
        )

        resume_file = gr.File(
            label="📄 Upload Resume",
            file_types=[".pdf", ".txt"],
            type="filepath"
        )

        analyze_resume_button = gr.Button(
            "🧠 Analyze My Resume",
            variant="primary"
        )

        resume_summary = gr.Markdown()

        detected_skills = gr.Textbox(
            label="💻 Detected Skills",
            interactive=False
        )

        overall_match = gr.Number(
            label="🎯 Overall Resume Match %",
            interactive=False
        )

        resume_results = gr.Dataframe(
            label="📊 Resume → Opportunity Matching",
            interactive=False
        )

        recommendations = gr.Markdown()

        analyze_resume_button.click(
            fn=analyze_uploaded_resume,
            inputs=resume_file,
            outputs=[
                resume_summary,
                detected_skills,
                overall_match,
                resume_results,
                recommendations
            ]
        )


    # ========================================================
    # TAB 3 — OPPORTUNITY INTELLIGENCE
    # ========================================================

    with gr.Tab("🏆 Opportunity Intelligence"):

        gr.Markdown(
            """
## 🏆 Opportunity Intelligence

**Relevance + Profile Match + Skill Alignment → CareerPilot Score**
"""
        )

        user_skills_input = gr.Textbox(
            label="💻 Your Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        analyze_opportunity_button = gr.Button(
            "🏆 Find My Best Opportunities",
            variant="primary"
        )

        best_opportunity = gr.Markdown()

        opportunity_table = gr.Dataframe(
            label="📊 Ranked Opportunity Intelligence",
            interactive=False
        )

        analyze_opportunity_button.click(
            fn=analyze_opportunities,
            inputs=user_skills_input,
            outputs=[
                best_opportunity,
                opportunity_table
            ]
        )


    # ========================================================
    # TAB 4 — INTERVIEW SIMULATOR
    # ========================================================

    with gr.Tab("🤖 Interview Simulator"):

        gr.Markdown(
            """
## 🤖 CareerPilot Interview Simulator

Prepare for interviews based on your **career goal and skills**.

**Generate → Answer → Evaluate → Improve**
"""
        )

        interview_goal = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        interview_skills = gr.Textbox(
            label="💻 Your Skills",
            value="Python, Java, Machine Learning, AI, NLP"
        )

        question_count = gr.Slider(
            minimum=1,
            maximum=10,
            value=5,
            step=1,
            label="🔢 Number of Questions"
        )

        generate_button = gr.Button(
            "🤖 Generate Interview",
            variant="primary"
        )

        questions_output = gr.Markdown(
            label="📋 Interview Questions"
        )

        generate_button.click(
            fn=create_interview,
            inputs=[
                interview_goal,
                interview_skills,
                question_count
            ],
            outputs=questions_output
        )

        gr.Markdown("---")

        gr.Markdown(
            "### 📝 Practice Your Answer"
        )

        interview_question = gr.Textbox(
            label="Question",
            placeholder="Paste the interview question here..."
        )

        interview_answer = gr.Textbox(
            label="Your Answer",
            placeholder="Type your answer here...",
            lines=6
        )

        evaluate_button = gr.Button(
            "🧠 Evaluate My Answer",
            variant="primary"
        )

        evaluation = gr.Markdown(
            label="📊 Evaluation"
        )

        answer_score = gr.Number(
            label="⭐ Score / 100",
            interactive=False
        )

        improvement = gr.Markdown(
            label="📌 Improvement"
        )

        evaluate_button.click(
            fn=evaluate_answer,
            inputs=[
                interview_question,
                interview_answer
            ],
            outputs=[
                evaluation,
                answer_score,
                improvement
            ]
        )


    # ========================================================
    # FOOTER
    # ========================================================

    gr.Markdown(
        """
---

### 🔄 CareerPilot X

**Discover → Analyze → Match → Decide → Act → Improve**

Built with **Python + Gradio + SerpApi**
"""
    )


demo.launch(
    share=True,
    debug=True
)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://505f57031a51e19cb5.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7866 <> https://505f57031a51e19cb5.gradio.live

In [49]:
# ============================================================
# 🔮 CAREERPILOT X — WHAT-IF CAREER LAB
# ============================================================

import pandas as pd

def what_if_career_lab(
    career_goal,
    current_skills,
    additional_skills,
    target_role=None
):
    try:
        career_goal = str(career_goal).strip()
        current_skills = str(current_skills).strip()
        additional_skills = str(additional_skills).strip()

        # Convert skills into clean sets
        current = {
            x.strip().lower()
            for x in current_skills.split(",")
            if x.strip()
        }

        additional = {
            x.strip().lower()
            for x in additional_skills.split(",")
            if x.strip()
        }

        combined = current.union(additional)

        if target_role:
            target = str(target_role).strip()
        else:
            target = career_goal

        # ----------------------------------------------------
        # Skill importance by career
        # ----------------------------------------------------
        role_skills = {
            "ai/ml": [
                "python", "machine learning", "deep learning",
                "numpy", "pandas", "nlp", "tensorflow",
                "pytorch", "generative ai", "rag"
            ],
            "data science": [
                "python", "sql", "pandas", "numpy",
                "statistics", "machine learning",
                "data analysis", "power bi"
            ],
            "data analyst": [
                "sql", "excel", "python", "pandas",
                "power bi", "tableau", "data analysis"
            ],
            "software developer": [
                "python", "java", "c++", "sql",
                "git", "github", "data structures",
                "algorithms"
            ],
            "cybersecurity": [
                "python", "linux", "networking",
                "cybersecurity", "sql", "ethical hacking"
            ],
            "cloud": [
                "python", "linux", "aws",
                "azure", "docker", "kubernetes"
            ]
        }

        role_key = target.lower()

        selected_skills = []

        for role, skills in role_skills.items():
            if role in role_key or role_key in role:
                selected_skills = skills
                break

        if not selected_skills:
            selected_skills = [
                "python",
                "machine learning",
                "sql",
                "git",
                "generative ai",
                "rag"
            ]

        # ----------------------------------------------------
        # Current vs future match
        # ----------------------------------------------------
        current_match = set(selected_skills).intersection(current)
        future_match = set(selected_skills).intersection(combined)

        current_score = round(
            len(current_match) / len(selected_skills) * 100,
            1
        )

        future_score = round(
            len(future_match) / len(selected_skills) * 100,
            1
        )

        improvement = round(
            future_score - current_score,
            1
        )

        # ----------------------------------------------------
        # Newly valuable skills
        # ----------------------------------------------------
        newly_added = sorted(
            set(additional).intersection(selected_skills)
        )

        remaining_gaps = sorted(
            set(selected_skills).difference(combined)
        )

        # ----------------------------------------------------
        # Impact level
        # ----------------------------------------------------
        if improvement >= 30:
            impact = "🚀 VERY HIGH IMPACT"
        elif improvement >= 15:
            impact = "🔥 HIGH IMPACT"
        elif improvement > 0:
            impact = "🟡 MODERATE IMPACT"
        else:
            impact = "⚪ LOW IMPACT"

        # ----------------------------------------------------
        # Recommendation
        # ----------------------------------------------------
        if remaining_gaps:
            next_steps = "\n".join(
                f"{i+1}. 📚 Learn **{skill.title()}**"
                for i, skill in enumerate(remaining_gaps[:5])
            )
        else:
            next_steps = "🎉 No major skill gaps detected for this target."

        # ----------------------------------------------------
        # Skill comparison table
        # ----------------------------------------------------
        rows = []

        for skill in selected_skills:
            if skill in current:
                status = "✅ Already have"
            elif skill in additional:
                status = "🚀 Added in What-If"
            else:
                status = "📚 Missing"

            rows.append({
                "Skill": skill.title(),
                "Current Profile": "✅" if skill in current else "❌",
                "After What-If": "✅" if skill in combined else "❌",
                "Status": status
            })

        comparison_df = pd.DataFrame(rows)

        # ----------------------------------------------------
        # Final report
        # ----------------------------------------------------
        report = f"""
## 🔮 What-If Career Lab

### 🎯 Target Career
**{target}**

### 🧪 Scenario
Current Skills:

**{current_skills or "None provided"}**

Additional Skills:

**{additional_skills or "None provided"}**

---

## 📊 Career Match Simulation

| Metric | Current | After What-If |
|---|---:|---:|
| Career Match | **{current_score}%** | **{future_score}%** |
| Improvement | — | **+{improvement}%** |

### {impact}

---

## 🚀 Skills That Created the Improvement

{", ".join(x.title() for x in newly_added)
if newly_added else "No major target-role skills were added."}

---

## 📚 Remaining Skill Gaps

{", ".join(x.title() for x in remaining_gaps)
if remaining_gaps else "No major gaps detected."}

---

## 🧭 Recommended Next Steps

{next_steps}

---

### 🧠 CareerPilot Reasoning

CareerPilot simulated the target career using the selected
skill requirements and compared your current profile against
the hypothetical upgraded profile.

**Current → Scenario → Match Improvement → Remaining Gaps**
"""

        return report, comparison_df

    except Exception as e:
        return (
            f"❌ What-If Lab Error: {type(e).__name__}: {str(e)}",
            pd.DataFrame()
        )

print("✅ What-If Career Lab created successfully!")

✅ What-If Career Lab created successfully!

In [50]:
# 🔮 TEST WHAT-IF CAREER LAB

report, comparison = what_if_career_lab(
    career_goal="AI/ML internships",
    current_skills="Python, Java, AI, Machine Learning, NLP",
    additional_skills="Generative AI, RAG, SQL"
)

print(report)
print("\n📊 SKILL COMPARISON:")
display(comparison)

## 🔮 What-If Career Lab

### 🎯 Target Career
**AI/ML internships**

### 🧪 Scenario
Current Skills:

**Python, Java, AI, Machine Learning, NLP**

Additional Skills:

**Generative AI, RAG, SQL**

---

## 📊 Career Match Simulation

| Metric | Current | After What-If |
|---|---:|---:|
| Career Match | **30.0%** | **50.0%** |
| Improvement | — | **+20.0%** |

### 🔥 HIGH IMPACT

---

## 🚀 Skills That Created the Improvement

Generative Ai, Rag

---

## 📚 Remaining Skill Gaps

Deep Learning, Numpy, Pandas, Pytorch, Tensorflow

---

## 🧭 Recommended Next Steps

1. 📚 Learn **Deep Learning**
2. 📚 Learn **Numpy**
3. 📚 Learn **Pandas**
4. 📚 Learn **Pytorch**
5. 📚 Learn **Tensorflow**

---

### 🧠 CareerPilot Reasoning

CareerPilot simulated the target career using the selected
skill requirements and compared your current profile against
the hypothetical upgraded profile.

**Current → Scenario → Match Improvement → Remaining Gaps**


📊 SKILL COMPARISON:

              Skill Current Profile After What-If              Status
0            Python               ✅             ✅      ✅ Already have
1  Machine Learning               ✅             ✅      ✅ Already have
2     Deep Learning               ❌             ❌           📚 Missing
3             Numpy               ❌             ❌           📚 Missing
4            Pandas               ❌             ❌           📚 Missing
5               Nlp               ✅             ✅      ✅ Already have
6        Tensorflow               ❌             ❌           📚 Missing
7           Pytorch               ❌             ❌           📚 Missing
8     Generative Ai               ❌             ✅  🚀 Added in What-If
9               Rag               ❌             ✅  🚀 Added in What-If

In [51]:
# ============================================================
# 🧬 CAREERPILOT X — OPPORTUNITY DNA
# ============================================================

import pandas as pd

def opportunity_dna(opportunities, index=0):

    try:
        # Convert to DataFrame if needed
        if opportunities is None:
            return "❌ No opportunities available.", pd.DataFrame()

        if not isinstance(opportunities, pd.DataFrame):
            opportunities = pd.DataFrame(opportunities)

        if opportunities.empty:
            return "❌ No opportunities found. Run Career Mission first.", pd.DataFrame()

        # Keep index safe
        index = int(index)
        index = max(0, min(index, len(opportunities) - 1))

        row = opportunities.iloc[index]

        # Basic information
        title = str(row.get("Opportunity", "Unknown Opportunity"))
        source = str(row.get("Source", "Unknown"))

        # Scores
        try:
            relevance = float(row.get("Relevance %", 0))
        except:
            relevance = 0

        try:
            match = float(row.get("Match %", 0))
        except:
            match = 0

        try:
            confidence = float(row.get("Confidence %", 0))
        except:
            confidence = 0

        # Signals
        remote = str(row.get("Remote", row.get("Remote Signal", "Unknown")))
        risk = str(row.get("Risk", "Unknown"))

        # ----------------------------------------------------
        # Skill analysis
        # ----------------------------------------------------

        title_text = title.lower()

        known_skills = [
            "python",
            "java",
            "c++",
            "sql",
            "machine learning",
            "deep learning",
            "artificial intelligence",
            "ai",
            "ml",
            "nlp",
            "tensorflow",
            "pytorch",
            "pandas",
            "numpy",
            "generative ai",
            "genai",
            "rag",
            "langchain",
            "llm",
            "data science",
            "data analysis",
            "power bi",
            "tableau",
            "aws",
            "azure",
            "docker",
            "kubernetes"
        ]

        detected_skills = [
            skill for skill in known_skills
            if skill in title_text
        ]

        # Remove duplicates
        detected_skills = list(dict.fromkeys(detected_skills))

        # ----------------------------------------------------
        # DNA components
        # ----------------------------------------------------

        components = [
            {
                "DNA Component": "🎯 Relevance",
                "Score": relevance,
                "Meaning": "How closely the opportunity matches the career search."
            },
            {
                "DNA Component": "🧠 Profile Match",
                "Score": match,
                "Meaning": "How well the opportunity matches the user's profile."
            },
            {
                "DNA Component": "🔎 Source Confidence",
                "Score": confidence,
                "Meaning": "Confidence signal based on the source and available data."
            }
        ]

        # Skill signal
        skill_score = min(100, len(detected_skills) * 20)

        components.append({
            "DNA Component": "💻 Skill Signal",
            "Score": skill_score,
            "Meaning": "Technical skills detected directly from the opportunity."
        })

        # Overall DNA score
        dna_score = round(
            relevance * 0.35 +
            match * 0.35 +
            confidence * 0.20 +
            skill_score * 0.10,
            1
        )

        # Priority
        if dna_score >= 80:
            priority = "🔥 HIGH"
        elif dna_score >= 60:
            priority = "🟡 MEDIUM"
        else:
            priority = "⚪ LOW"

        # ----------------------------------------------------
        # Strengths
        # ----------------------------------------------------

        strengths = []

        if relevance >= 75:
            strengths.append("Strong career relevance")

        if match >= 70:
            strengths.append("Strong profile match")

        if confidence >= 80:
            strengths.append("Strong source confidence")

        if detected_skills:
            strengths.append(
                "Relevant skills detected: " +
                ", ".join(x.title() for x in detected_skills)
            )

        if "remote" in remote.lower():
            strengths.append("Remote-work signal detected")

        if not strengths:
            strengths.append("No major strength signals detected")

        # ----------------------------------------------------
        # Gaps / concerns
        # ----------------------------------------------------

        concerns = []

        if relevance < 60:
            concerns.append("Low career relevance")

        if match < 60:
            concerns.append("Profile match could be stronger")

        if confidence < 70:
            concerns.append("Limited source confidence")

        if remote.lower() in ["unknown", "unknown signal"]:
            concerns.append("Remote status is unclear")

        if not detected_skills:
            concerns.append("Few technical skills detected from the title")

        if not concerns:
            concerns.append("No major warning signals detected")

        # ----------------------------------------------------
        # Explanation
        # ----------------------------------------------------

        report = f"""
## 🧬 Opportunity DNA

### 🏆 Opportunity

**{title}**

**Source:** {source}

---

## 🧬 CareerPilot DNA Score

# **{dna_score}/100**

### Priority
**{priority}**

---

## 🔬 DNA Breakdown

"""

        for component in components:
            report += (
                f"### {component['DNA Component']}\n"
                f"**{component['Score']:.1f}%**\n\n"
                f"{component['Meaning']}\n\n"
            )

        report += f"""
---

## 💪 Strength Signals

"""

        for item in strengths:
            report += f"- ✅ {item}\n"

        report += f"""

---

## ⚠️ Gap / Risk Signals

"""

        for item in concerns:
            report += f"- ⚠️ {item}\n"

        report += f"""

---

## 🌐 Opportunity Signals

**Remote:** {remote}

**Risk Signal:** {risk}

**Source Confidence:** {confidence:.1f}%

---

## 💻 Skills Detected

{", ".join(x.title() for x in detected_skills)
if detected_skills else "No technical skills detected from the opportunity title."}

---

## 🧠 CareerPilot Decision

"""

        if dna_score >= 80:
            decision = "🔥 **HIGH PRIORITY** — This opportunity deserves strong consideration."
        elif dna_score >= 60:
            decision = "🟡 **MEDIUM PRIORITY** — Consider applying after reviewing the details."
        else:
            decision = "⚪ **LOW PRIORITY** — Consider other opportunities first."

        report += decision

        # ----------------------------------------------------
        # Comparison table
        # ----------------------------------------------------

        dna_table = pd.DataFrame(components)

        return report, dna_table

    except Exception as e:

        return (
            f"❌ Opportunity DNA Error: {type(e).__name__}: {str(e)}",
            pd.DataFrame()
        )


print("✅ Opportunity DNA created successfully!")

✅ Opportunity DNA created successfully!

In [53]:
# 🧬 OPPORTUNITY DNA — QUICK TEST

test_opportunities = pd.DataFrame([
    {
        "Opportunity": "AI/ML Intern - Python, Machine Learning, Generative AI",
        "Source": "Internshala",
        "Relevance %": 90,
        "Match %": 75,
        "Confidence %": 90,
        "Remote": "Likely Remote",
        "Risk": "🟢 Low signal"
    }
])

report, dna_table = opportunity_dna(
    test_opportunities,
    index=0
)

print(report)

print("\n📊 DNA BREAKDOWN:")
display(dna_table)

## 🧬 Opportunity DNA

### 🏆 Opportunity

**AI/ML Intern - Python, Machine Learning, Generative AI**

**Source:** Internshala

---

## 🧬 CareerPilot DNA Score

# **85.8/100**

### Priority
**🔥 HIGH**

---

## 🔬 DNA Breakdown

### 🎯 Relevance
**90.0%**

How closely the opportunity matches the career search.

### 🧠 Profile Match
**75.0%**

How well the opportunity matches the user's profile.

### 🔎 Source Confidence
**90.0%**

Confidence signal based on the source and available data.

### 💻 Skill Signal
**100.0%**

Technical skills detected directly from the opportunity.


---

## 💪 Strength Signals

- ✅ Strong career relevance
- ✅ Strong profile match
- ✅ Strong source confidence
- ✅ Relevant skills detected: Python, Machine Learning, Ai, Ml, Generative Ai
- ✅ Remote-work signal detected


---

## ⚠️ Gap / Risk Signals

- ⚠️ No major warning signals detected


---

## 🌐 Opportunity Signals

**Remote:** Likely Remote

**Risk Signal:** 🟢 Low signal

**Source Confidence:** 90.0%

---

## 💻 Skills Detected

Python, Machine Learning, Ai, Ml, Generative Ai

---

## 🧠 CareerPilot Decision

🔥 **HIGH PRIORITY** — This opportunity deserves strong consideration.

📊 DNA BREAKDOWN:

,DNA Component,Score,Meaning
0,🎯 Relevance,90.0,How closely the opportunity matches the career...
1,🧠 Profile Match,75.0,How well the opportunity matches the user's pr...
2,🔎 Source Confidence,90.0,Confidence signal based on the source and avai...
3,💻 Skill Signal,100.0,Technical skills detected directly from the op...

In [55]:
# ============================================================
# 🚀 CAREERPILOT X — UNIFIED 6-TAB DASHBOARD
# ============================================================

import gradio as gr
import pandas as pd

# ------------------------------------------------------------
# SHARED CACHE
# ------------------------------------------------------------

if "CAREER_MISSION_CACHE" not in globals():
    CAREER_MISSION_CACHE = {"opportunities": pd.DataFrame()}


# ------------------------------------------------------------
# CAREER MISSION
# ------------------------------------------------------------

def dashboard_career_mission(
    goal,
    education,
    skills,
    location,
    experience
):
    try:
        result = run_career_mission(
            goal,
            education,
            skills,
            location,
            experience
        )

        if isinstance(result, tuple) and len(result) == 6:
            opportunities = result[0]

            if isinstance(opportunities, pd.DataFrame):
                CAREER_MISSION_CACHE["opportunities"] = opportunities.copy()

        return result

    except Exception as e:
        return (
            pd.DataFrame(),
            f"❌ Career Mission Error: {type(e).__name__}: {str(e)}",
            "",
            "",
            "",
            ""
        )


# ------------------------------------------------------------
# RESUME INTELLIGENCE
# ------------------------------------------------------------

def dashboard_resume(resume_file):

    try:
        opportunities = CAREER_MISSION_CACHE.get(
            "opportunities",
            pd.DataFrame()
        )

        return resume_intelligence(
            resume_file,
            opportunities
        )

    except Exception as e:
        return (
            f"❌ Resume Error: {type(e).__name__}: {str(e)}",
            [],
            0,
            pd.DataFrame(),
            ""
        )


# ------------------------------------------------------------
# OPPORTUNITY INTELLIGENCE
# ------------------------------------------------------------

def dashboard_opportunity_intelligence(user_skills):

    try:
        opportunities = CAREER_MISSION_CACHE.get(
            "opportunities",
            pd.DataFrame()
        )

        if opportunities.empty:
            return (
                "❌ No opportunities available. "
                "Please run Career Mission first.",
                pd.DataFrame()
            )

        return opportunity_intelligence(
            opportunities,
            user_skills
        )

    except Exception as e:
        return (
            f"❌ Opportunity Intelligence Error: "
            f"{type(e).__name__}: {str(e)}",
            pd.DataFrame()
        )


# ------------------------------------------------------------
# INTERVIEW GENERATOR
# ------------------------------------------------------------

def dashboard_generate_interview(
    career_goal,
    skills,
    number_of_questions
):

    try:

        number_of_questions = int(number_of_questions)

        number_of_questions = max(
            1,
            min(10, number_of_questions)
        )

        return interview_session(
            career_goal,
            skills,
            number_of_questions
        )

    except Exception as e:

        return (
            f"❌ Interview generation error: "
            f"{type(e).__name__}: {str(e)}"
        )


# ------------------------------------------------------------
# INTERVIEW EVALUATION
# ------------------------------------------------------------

def dashboard_evaluate_answer(
    question,
    answer
):

    try:

        return evaluate_interview_answer(
            question,
            answer
        )

    except Exception as e:

        return (
            f"❌ Evaluation error: {str(e)}",
            0,
            "Please try again."
        )


# ------------------------------------------------------------
# WHAT-IF
# ------------------------------------------------------------

def dashboard_what_if(
    career_goal,
    current_skills,
    additional_skills,
    target_role
):

    try:

        return what_if_career_lab(
            career_goal,
            current_skills,
            additional_skills,
            target_role
        )

    except Exception as e:

        return (
            f"❌ What-If Error: {type(e).__name__}: {str(e)}",
            pd.DataFrame()
        )


# ------------------------------------------------------------
# OPPORTUNITY DNA
# ------------------------------------------------------------

def dashboard_opportunity_dna(index):

    try:

        opportunities = CAREER_MISSION_CACHE.get(
            "opportunities",
            pd.DataFrame()
        )

        if opportunities.empty:

            return (
                "❌ No opportunities available.\n\n"
                "Please run **Career Mission** first.",
                pd.DataFrame()
            )

        return opportunity_dna(
            opportunities,
            int(index)
        )

    except Exception as e:

        return (
            f"❌ Opportunity DNA Error: "
            f"{type(e).__name__}: {str(e)}",
            pd.DataFrame()
        )


# ============================================================
# BUILD DASHBOARD
# ============================================================

with gr.Blocks(
    title="CareerPilot X"
) as demo:

    gr.Markdown(
        """
# 🚀 CareerPilot X
### Autonomous Career Intelligence Platform

**Live Web Intelligence → Research → Match → Decide → Act**

Use the tabs below to explore your personalized career intelligence system.
"""
    )


    # ========================================================
    # TAB 1 — CAREER MISSION
    # ========================================================

    with gr.Tab("🎯 Career Mission"):

        gr.Markdown(
            """
## 🎯 Career Mission

Tell CareerPilot what career you're targeting.
It will research live opportunities using SerpApi.
"""
        )

        with gr.Row():

            goal = gr.Textbox(
                label="Career Goal",
                value="AI/ML internships"
            )

            education = gr.Textbox(
                label="Education",
                value="BTech CSE-AIML"
            )

        with gr.Row():

            skills = gr.Textbox(
                label="Skills",
                value="Python, Java, AI, Machine Learning, NLP"
            )

            location = gr.Textbox(
                label="Location",
                value="India"
            )

        experience = gr.Textbox(
            label="Experience",
            value="Student"
        )

        mission_button = gr.Button(
            "🚀 Start Career Mission",
            variant="primary"
        )

        mission_opportunities = gr.Dataframe(
            label="🔎 Live Opportunities",
            interactive=False
        )

        mission_summary = gr.Markdown()

        mission_skills = gr.Markdown()

        mission_market = gr.Markdown()

        mission_roadmap = gr.Markdown()

        mission_log = gr.Markdown()

        mission_button.click(
            dashboard_career_mission,
            inputs=[
                goal,
                education,
                skills,
                location,
                experience
            ],
            outputs=[
                mission_opportunities,
                mission_summary,
                mission_skills,
                mission_market,
                mission_roadmap,
                mission_log
            ]
        )


    # ========================================================
    # TAB 2 — RESUME INTELLIGENCE
    # ========================================================

    with gr.Tab("📄 Resume Intelligence"):

        gr.Markdown(
            """
## 📄 Resume Intelligence

Upload your resume and CareerPilot will analyze
your technical skills and compare them with researched opportunities.
"""
        )

        resume_file = gr.File(
            label="📎 Upload Resume",
            file_types=[".pdf", ".txt"],
            type="filepath"
        )

        resume_button = gr.Button(
            "🔍 Analyze Resume",
            variant="primary"
        )

        resume_summary = gr.Markdown()

        resume_skills = gr.JSON(
            label="💻 Detected Skills"
        )

        resume_score = gr.Number(
            label="🎯 Overall Resume Match"
        )

        resume_table = gr.Dataframe(
            label="📊 Opportunity Resume Match",
            interactive=False
        )

        resume_recommendations = gr.Markdown()

        resume_button.click(
            dashboard_resume,
            inputs=resume_file,
            outputs=[
                resume_summary,
                resume_skills,
                resume_score,
                resume_table,
                resume_recommendations
            ]
        )


    # ========================================================
    # TAB 3 — OPPORTUNITY INTELLIGENCE
    # ========================================================

    with gr.Tab("🏆 Opportunity Intelligence"):

        gr.Markdown(
            """
## 🏆 Opportunity Intelligence

Rank your researched opportunities using:
**Relevance + Profile Match + Skill Alignment**
"""
        )

        oi_skills = gr.Textbox(
            label="Your Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        oi_button = gr.Button(
            "🏆 Analyze Opportunities",
            variant="primary"
        )

        oi_summary = gr.Markdown()

        oi_table = gr.Dataframe(
            label="📊 Opportunity Ranking",
            interactive=False
        )

        oi_button.click(
            dashboard_opportunity_intelligence,
            inputs=oi_skills,
            outputs=[
                oi_summary,
                oi_table
            ]
        )


    # ========================================================
    # TAB 4 — INTERVIEW SIMULATOR
    # ========================================================

    with gr.Tab("🤖 Interview Simulator"):

        gr.Markdown(
            """
## 🤖 Interview Simulator

Practice technical interview questions based on your
career goal and skills.
"""
        )

        interview_goal = gr.Textbox(
            label="Career Goal",
            value="AI/ML Engineer"
        )

        interview_skills = gr.Textbox(
            label="Skills",
            value="Python, Machine Learning, NLP, Generative AI"
        )

        interview_count = gr.Slider(
            minimum=1,
            maximum=10,
            value=5,
            step=1,
            label="Number of Questions"
        )

        interview_generate = gr.Button(
            "🎤 Generate Interview",
            variant="primary"
        )

        interview_questions = gr.Markdown()

        interview_generate.click(
            dashboard_generate_interview,
            inputs=[
                interview_goal,
                interview_skills,
                interview_count
            ],
            outputs=interview_questions
        )

        gr.Markdown("---")

        interview_question = gr.Textbox(
            label="Question"
        )

        interview_answer = gr.Textbox(
            label="Your Answer",
            lines=6
        )

        interview_evaluate = gr.Button(
            "🧠 Evaluate Answer"
        )

        interview_feedback = gr.Markdown()

        interview_score = gr.Number(
            label="⭐ Score"
        )

        interview_tip = gr.Markdown()

        interview_evaluate.click(
            dashboard_evaluate_answer,
            inputs=[
                interview_question,
                interview_answer
            ],
            outputs=[
                interview_feedback,
                interview_score,
                interview_tip
            ]
        )


    # ========================================================
    # TAB 5 — WHAT IF
    # ========================================================

    with gr.Tab("🔮 What-If Career Lab"):

        gr.Markdown(
            """
## 🔮 What-If Career Lab

Simulate how learning new skills could change your
career readiness.
"""
        )

        whatif_goal = gr.Textbox(
            label="Career Goal",
            value="AI/ML internships"
        )

        whatif_current = gr.Textbox(
            label="Current Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        whatif_additional = gr.Textbox(
            label="Additional Skills to Simulate",
            value="Generative AI, RAG, SQL"
        )

        whatif_role = gr.Textbox(
            label="Target Role",
            value="AI/ML"
        )

        whatif_button = gr.Button(
            "🔮 Run What-If Simulation",
            variant="primary"
        )

        whatif_report = gr.Markdown()

        whatif_table = gr.Dataframe(
            label="📊 Skill Comparison",
            interactive=False
        )

        whatif_button.click(
            dashboard_what_if,
            inputs=[
                whatif_goal,
                whatif_current,
                whatif_additional,
                whatif_role
            ],
            outputs=[
                whatif_report,
                whatif_table
            ]
        )


    # ========================================================
    # TAB 6 — OPPORTUNITY DNA
    # ========================================================

    with gr.Tab("🧬 Opportunity DNA"):

        gr.Markdown(
            """
## 🧬 Opportunity DNA

Understand WHY an opportunity is recommended,
instead of seeing only a single match percentage.

Run Career Mission first.
"""
        )

        dna_index = gr.Number(
            label="Opportunity Number",
            value=0,
            precision=0
        )

        dna_button = gr.Button(
            "🧬 Analyze Opportunity DNA",
            variant="primary"
        )

        dna_report = gr.Markdown()

        dna_table = gr.Dataframe(
            label="🔬 DNA Breakdown",
            interactive=False
        )

        dna_button.click(
            dashboard_opportunity_dna,
            inputs=dna_index,
            outputs=[
                dna_report,
                dna_table
            ]
        )


    # ========================================================
    # FOOTER
    # ========================================================

    gr.Markdown(
        """
---

### 🚀 CareerPilot X

**Understand → Research → Reason → Decide → Act → Improve**

Built with **Python + Gradio + SerpApi**
"""
    )


print("✅ CareerPilot X 6-tab dashboard created!")

demo.launch(
    share=True,
    debug=True
)

✅ CareerPilot X 6-tab dashboard created!
Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://a79d4b907269e0b04f.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7866 <> https://a79d4b907269e0b04f.gradio.live

In [57]:
# ============================================================
# 🧬 CAREERPILOT X — SMART SKILL DETECTOR
# ============================================================

import re

SKILL_ALIASES = {
    "Python": ["python"],
    "Java": ["java"],
    "C++": ["c++", "cpp"],
    "SQL": ["sql", "mysql", "postgresql", "postgres"],

    "Artificial Intelligence": [
        "artificial intelligence",
        "ai"
    ],

    "Machine Learning": [
        "machine learning",
        "ml"
    ],

    "Deep Learning": [
        "deep learning"
    ],

    "NLP": [
        "nlp",
        "natural language processing"
    ],

    "Generative AI": [
        "generative ai",
        "genai",
        "gen ai"
    ],

    "RAG": [
        "rag",
        "retrieval augmented generation",
        "retrieval-augmented generation"
    ],

    "LLM": [
        "llm",
        "large language model",
        "large language models"
    ],

    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],

    "Scikit-learn": [
        "scikit-learn",
        "sklearn"
    ],

    "LangChain": ["langchain"],

    "Computer Vision": [
        "computer vision",
        "opencv"
    ],

    "Data Science": ["data science"],
    "Data Analysis": [
        "data analysis",
        "data analytics"
    ],

    "Power BI": ["power bi"],
    "Tableau": ["tableau"],
    "Git": ["git", "github"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Linux": ["linux"]
}


def detect_opportunity_skills(text):

    text = str(text).lower()

    found = []

    for skill, aliases in SKILL_ALIASES.items():

        for alias in aliases:

            pattern = r"(?<!\w)" + re.escape(alias) + r"(?!\w)"

            if re.search(pattern, text):
                found.append(skill)
                break

    return sorted(set(found))


# ============================================================
# 🧪 AUTOMATIC TEST
# ============================================================

test_text = """
AI/ML Intern required skills:
Python, machine learning, deep learning,
NLP, Generative AI, RAG, SQL, TensorFlow and PyTorch.
"""

skills_found = detect_opportunity_skills(test_text)

print("✅ Smart Skill Detector is working!")
print("\n🔎 Skills detected:")

for skill in skills_found:
    print("  ✅", skill)

print("\nTotal skills detected:", len(skills_found))

✅ Smart Skill Detector is working!

🔎 Skills detected:
  ✅ Artificial Intelligence
  ✅ Deep Learning
  ✅ Generative AI
  ✅ Machine Learning
  ✅ NLP
  ✅ PyTorch
  ✅ Python
  ✅ RAG
  ✅ SQL
  ✅ TensorFlow

Total skills detected: 10

In [58]:
# ============================================================
# 🧬 CAREERPILOT X — SMART OPPORTUNITY DNA
# ============================================================

import pandas as pd

def opportunity_dna(opportunities, index=0):

    # Check data
    if opportunities is None:
        return "❌ No opportunities available.", pd.DataFrame()

    if not isinstance(opportunities, pd.DataFrame):
        try:
            opportunities = pd.DataFrame(opportunities)
        except:
            return "❌ Could not process opportunities.", pd.DataFrame()

    if opportunities.empty:
        return "❌ No opportunities found. Run Career Mission first.", pd.DataFrame()

    # Safe index
    index = int(index)

    if index < 0:
        index = 0

    if index >= len(opportunities):
        index = 0

    row = opportunities.iloc[index]

    # --------------------------------------------------------
    # Read ALL available opportunity information
    # --------------------------------------------------------

    text_parts = []

    for column in opportunities.columns:
        value = row.get(column, "")
        if pd.notna(value):
            text_parts.append(str(value))

    opportunity_text = " ".join(text_parts)

    # --------------------------------------------------------
    # Smart skill detection
    # --------------------------------------------------------

    detected_skills = detect_opportunity_skills(opportunity_text)

    # --------------------------------------------------------
    # Read scores
    # --------------------------------------------------------

    def safe_float(value, default=0):
        try:
            return float(value)
        except:
            return default

    relevance = safe_float(row.get("Relevance %", 0))
    match = safe_float(row.get("Match %", 0))
    confidence = safe_float(row.get("Confidence %", 0))

    # --------------------------------------------------------
    # Skill signal
    # --------------------------------------------------------

    if len(detected_skills) == 0:
        skill_signal = 0
    elif len(detected_skills) <= 2:
        skill_signal = 40
    elif len(detected_skills) <= 4:
        skill_signal = 60
    elif len(detected_skills) <= 6:
        skill_signal = 75
    elif len(detected_skills) <= 8:
        skill_signal = 90
    else:
        skill_signal = 100

    # --------------------------------------------------------
    # Remote signal
    # --------------------------------------------------------

    lower_text = opportunity_text.lower()

    if any(x in lower_text for x in [
        "remote",
        "work from home",
        "wfh",
        "remote internship"
    ]):
        remote_signal = "🌐 Likely Remote"

    elif any(x in lower_text for x in [
        "on-site",
        "onsite",
        "office"
    ]):
        remote_signal = "🏢 Likely On-site"

    else:
        remote_signal = "❓ On-site/Unknown"

    # --------------------------------------------------------
    # Risk signal
    # --------------------------------------------------------

    if any(x in lower_text for x in [
        "pay to apply",
        "registration fee",
        "joining fee",
        "deposit required"
    ]):
        risk_signal = "🔴 Potential warning"

    elif any(x in lower_text for x in [
        "internship",
        "career",
        "jobs",
        "hiring"
    ]):
        risk_signal = "🟢 Low signal"

    else:
        risk_signal = "🟡 Review manually"

    # --------------------------------------------------------
    # DNA SCORE
    # --------------------------------------------------------

    dna_score = round(
        relevance * 0.30 +
        match * 0.30 +
        confidence * 0.20 +
        skill_signal * 0.20,
        1
    )

    if dna_score >= 80:
        priority = "🔥 HIGH"
    elif dna_score >= 65:
        priority = "🟡 MEDIUM"
    else:
        priority = "⚪ LOW"

    # --------------------------------------------------------
    # Skills display
    # --------------------------------------------------------

    skills_text = (
        ", ".join(detected_skills)
        if detected_skills
        else "No recognised technical skills detected."
    )

    # --------------------------------------------------------
    # Report
    # --------------------------------------------------------

    title = str(row.get("Opportunity", "Unknown Opportunity"))
    source = str(row.get("Source", "Unknown"))

    report = f"""
## 🧬 CareerPilot Opportunity DNA

### 🎯 Opportunity
**{title}**

### 🌐 Source
**{source}**

---

### ⭐ DNA Score
# **{dna_score}/100**

### 🚦 Priority
**{priority}**

---

### 🔎 Relevance
**{relevance}%**

### 🧠 Profile Match
**{match}%**

### 🛡️ Source Confidence
**{confidence}%**

### 💻 Skill Signal
**{skill_signal}%**

---

### 💪 Strengths

- Strong opportunity relevance
- Profile compatibility: **{match}%**
- Source confidence: **{confidence}%**
- **{len(detected_skills)} technical skill signals detected**

### 🧠 Skills Detected

**{skills_text}**

### 🌐 Work Mode

{remote_signal}

### ⚠️ Risk Signal

{risk_signal}

---

### 🤖 CareerPilot Decision

**{priority} PRIORITY**

CareerPilot combines:

**Relevance + Profile Match + Source Confidence + Skill Signals**

to create the Opportunity DNA score.
"""

    # --------------------------------------------------------
    # DNA TABLE
    # --------------------------------------------------------

    dna_table = pd.DataFrame([{
        "Opportunity": title,
        "DNA Score": dna_score,
        "Priority": priority,
        "Relevance": relevance,
        "Profile Match": match,
        "Confidence": confidence,
        "Skill Signal": skill_signal,
        "Skills Detected": ", ".join(detected_skills),
        "Remote": remote_signal,
        "Risk Signal": risk_signal
    }])

    return report, dna_table


print("✅ Smart Opportunity DNA created!")

✅ Smart Opportunity DNA created!

In [59]:
# Test using the opportunities from your last Career Mission

if "CAREER_MISSION_CACHE" in globals() and not CAREER_MISSION_CACHE["opportunities"].empty:

    dna_report, dna_table = opportunity_dna(
        CAREER_MISSION_CACHE["opportunities"],
        0
    )

    print(dna_report)
    print("\n📊 DNA TABLE")
    display(dna_table)

else:
    print("⚠️ Run Career Mission once first.")

## 🧬 CareerPilot Opportunity DNA

### 🎯 Opportunity
**Ai Internships jobs in Chennai, Tamil Nadu**

### 🌐 Source
**in.indeed.com**

---

### ⭐ DNA Score
# **65.9/100**

### 🚦 Priority
**🟡 MEDIUM**

---

### 🔎 Relevance
**70.0%**

### 🧠 Profile Match
**61.0%**

### 🛡️ Source Confidence
**93.0%**

### 💻 Skill Signal
**40%**

---

### 💪 Strengths

- Strong opportunity relevance
- Profile compatibility: **61.0%**
- Source confidence: **93.0%**
- **1 technical skill signals detected**

### 🧠 Skills Detected

**Artificial Intelligence**

### 🌐 Work Mode

🏢 Likely On-site

### ⚠️ Risk Signal

🟢 Low signal

---

### 🤖 CareerPilot Decision

**🟡 MEDIUM PRIORITY**

CareerPilot combines:

**Relevance + Profile Match + Source Confidence + Skill Signals**

to create the Opportunity DNA score.


📊 DNA TABLE

,Opportunity,DNA Score,Priority,Relevance,Profile Match,Confidence,Skill Signal,Skills Detected,Remote,Risk Signal
0,"Ai Internships jobs in Chennai, Tamil Nadu",65.9,🟡 MEDIUM,70.0,61.0,93.0,40,Artificial Intelligence,🏢 Likely On-site,🟢 Low signal

In [60]:
# ============================================================
# 📈 CAREERPILOT X — CAREER MARKET INTELLIGENCE
# ============================================================

import pandas as pd
import re
from collections import Counter

def career_market_intelligence(opportunities):

    if opportunities is None:
        return "❌ No opportunities available.", pd.DataFrame()

    if not isinstance(opportunities, pd.DataFrame):
        try:
            opportunities = pd.DataFrame(opportunities)
        except:
            return "❌ Could not process opportunities.", pd.DataFrame()

    if opportunities.empty:
        return "❌ No opportunities found. Run Career Mission first.", pd.DataFrame()

    # --------------------------------------------------------
    # Combine all useful opportunity text
    # --------------------------------------------------------

    text_data = []

    for _, row in opportunities.iterrows():

        row_text = ""

        for column in opportunities.columns:
            value = row.get(column, "")

            if pd.notna(value):
                row_text += " " + str(value)

        text_data.append(row_text.lower())

    combined_text = " ".join(text_data)

    # --------------------------------------------------------
    # Detect market skills
    # --------------------------------------------------------

    market_skills = {}

    for skill, aliases in SKILL_ALIASES.items():

        count = 0

        for text in text_data:

            found = False

            for alias in aliases:

                pattern = r"(?<!\w)" + re.escape(alias) + r"(?!\w)"

                if re.search(pattern, text):
                    found = True
                    break

            if found:
                count += 1

        if count > 0:
            market_skills[skill] = count

    # --------------------------------------------------------
    # Sort skills by demand
    # --------------------------------------------------------

    sorted_skills = sorted(
        market_skills.items(),
        key=lambda x: x[1],
        reverse=True
    )

    # --------------------------------------------------------
    # User skills
    # --------------------------------------------------------

    user_skills = set()

    if "CAREER_MISSION_CACHE" in globals():

        # We intentionally don't assume a specific UI input here.
        # Current market intelligence is based on live opportunities.
        pass

    # --------------------------------------------------------
    # Demand table
    # --------------------------------------------------------

    demand_rows = []

    total_opportunities = len(opportunities)

    for skill, count in sorted_skills:

        percentage = round(
            (count / total_opportunities) * 100,
            1
        )

        demand_rows.append({
            "Skill": skill,
            "Opportunity Signals": count,
            "Market Demand %": percentage
        })

    demand_table = pd.DataFrame(demand_rows)

    # --------------------------------------------------------
    # Top skills
    # --------------------------------------------------------

    if sorted_skills:

        top_skills = sorted_skills[:8]

        top_skill_text = "\n".join(
            [
                f"{i+1}. **{skill}** — {count} opportunity signal(s)"
                for i, (skill, count) in enumerate(top_skills)
            ]
        )

        strongest_skill = sorted_skills[0][0]

    else:

        top_skill_text = "No recognised technical skill signals found."
        strongest_skill = "Not enough data"

    # --------------------------------------------------------
    # Career direction
    # --------------------------------------------------------

    ai_count = 0
    data_count = 0
    software_count = 0

    for text in text_data:

        if any(x in text for x in [
            "artificial intelligence",
            "machine learning",
            "ai/ml",
            "generative ai",
            "deep learning",
            "nlp"
        ]):
            ai_count += 1

        if any(x in text for x in [
            "data science",
            "data analyst",
            "data analysis",
            "sql",
            "power bi",
            "tableau"
        ]):
            data_count += 1

        if any(x in text for x in [
            "software developer",
            "software engineer",
            "java developer",
            "python developer",
            "web developer"
        ]):
            software_count += 1

    directions = {
        "AI / ML": ai_count,
        "Data": data_count,
        "Software Development": software_count
    }

    best_direction = max(
        directions,
        key=directions.get
    )

    # --------------------------------------------------------
    # Market strength
    # --------------------------------------------------------

    if total_opportunities >= 10:
        market_strength = "🔥 Strong"
    elif total_opportunities >= 5:
        market_strength = "🟢 Moderate"
    else:
        market_strength = "🟡 Limited sample"

    # --------------------------------------------------------
    # Report
    # --------------------------------------------------------

    report = f"""
## 📈 CareerPilot Market Intelligence

### 🌐 Live Market Sample

**{total_opportunities} opportunities analyzed**

### 📊 Market Strength

**{market_strength}**

---

### 🔥 Most Demanded Skills

{top_skill_text}

---

### 🏆 Strongest Market Skill

**{strongest_skill}**

---

### 🎯 Strongest Career Direction

**{best_direction}**

### Direction Signals

- 🤖 AI / ML — **{ai_count}**
- 📊 Data — **{data_count}**
- 💻 Software Development — **{software_count}**

---

### 🧠 CareerPilot Insight

The market signals suggest focusing your preparation around:

**{strongest_skill}**

CareerPilot derives these signals from the live opportunity data collected through **SerpApi**, rather than using a fixed static list.

> ⚠️ Market demand percentages represent signals in the current search sample, not the entire job market.
"""

    return report, demand_table


print("✅ Career Market Intelligence created!")

✅ Career Market Intelligence created!

In [61]:
# ============================================================
# 🧪 TEST CAREER MARKET INTELLIGENCE
# ============================================================

if "CAREER_MISSION_CACHE" in globals():

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    market_report, market_table = career_market_intelligence(
        opportunities
    )

    print(market_report)

    print("\n📊 MARKET DEMAND TABLE")
    display(market_table)

else:

    print("⚠️ CAREER_MISSION_CACHE not found.")
    print("Run Career Mission once first.")

## 📈 CareerPilot Market Intelligence

### 🌐 Live Market Sample

**5 opportunities analyzed**

### 📊 Market Strength

**🟢 Moderate**

---

### 🔥 Most Demanded Skills

1. **Artificial Intelligence** — 5 opportunity signal(s)
2. **Machine Learning** — 2 opportunity signal(s)

---

### 🏆 Strongest Market Skill

**Artificial Intelligence**

---

### 🎯 Strongest Career Direction

**AI / ML**

### Direction Signals

- 🤖 AI / ML — **1**
- 📊 Data — **0**
- 💻 Software Development — **0**

---

### 🧠 CareerPilot Insight

The market signals suggest focusing your preparation around:

**Artificial Intelligence**

CareerPilot derives these signals from the live opportunity data collected through **SerpApi**, rather than using a fixed static list.

> ⚠️ Market demand percentages represent signals in the current search sample, not the entire job market.


📊 MARKET DEMAND TABLE

                     Skill  Opportunity Signals  Market Demand %
0  Artificial Intelligence                    5            100.0
1         Machine Learning                    2             40.0

In [62]:
# ============================================================
# 🗺️ CAREERPILOT X — PERSONALIZED CAREER ROADMAP
# ============================================================

def career_roadmap(
    career_goal,
    current_skills,
    market_table=None
):

    goal = str(career_goal).strip()
    skills_text = str(current_skills).lower()

    # --------------------------------------------------------
    # Normalize user skills
    # --------------------------------------------------------

    user_skills = set()

    for skill in SKILL_ALIASES.keys():

        aliases = SKILL_ALIASES[skill]

        for alias in aliases:

            if alias.lower() in skills_text:
                user_skills.add(skill)
                break

    # --------------------------------------------------------
    # Market skills
    # --------------------------------------------------------

    market_skills = []

    if isinstance(market_table, pd.DataFrame):

        if not market_table.empty and "Skill" in market_table.columns:

            market_skills = market_table["Skill"].astype(str).tolist()

    # --------------------------------------------------------
    # Identify gaps
    # --------------------------------------------------------

    gaps = [
        skill
        for skill in market_skills
        if skill not in user_skills
    ]

    # Remove duplicates
    gaps = list(dict.fromkeys(gaps))

    # --------------------------------------------------------
    # Learning priorities
    # --------------------------------------------------------

    priority_skills = gaps[:6]

    if not priority_skills:
        priority_skills = [
            "Machine Learning",
            "Generative AI",
            "RAG",
            "SQL"
        ]

    # --------------------------------------------------------
    # Roadmap stages
    # --------------------------------------------------------

    roadmap = []

    roadmap.append(
        "1️⃣ **Strengthen your current foundation**\n"
        "Practice Python, programming fundamentals and problem solving."
    )

    for i, skill in enumerate(priority_skills, start=2):

        roadmap.append(
            f"{i}️⃣ **Learn {skill}**\n"
            f"Understand the fundamentals and build small practical examples."
        )

    project_number = len(roadmap) + 1

    roadmap.append(
        f"{project_number}️⃣ **Build 2–3 portfolio projects**\n"
        "Create projects that demonstrate the skills demanded by the market."
    )

    project_number += 1

    roadmap.append(
        f"{project_number}️⃣ **Publish your projects**\n"
        "Upload clean projects to GitHub with README files, screenshots and setup instructions."
    )

    project_number += 1

    roadmap.append(
        f"{project_number}️⃣ **Prepare your resume**\n"
        "Highlight measurable project results and relevant technical skills."
    )

    project_number += 1

    roadmap.append(
        f"{project_number}️⃣ **Prepare for interviews**\n"
        "Practice technical questions, project explanations and behavioral questions."
    )

    project_number += 1

    roadmap.append(
        f"{project_number}️⃣ **Apply consistently**\n"
        "Track applications and prioritize opportunities with the highest CareerPilot scores."
    )

    # --------------------------------------------------------
    # Goal-specific recommendation
    # --------------------------------------------------------

    goal_lower = goal.lower()

    if "ai" in goal_lower or "machine learning" in goal_lower:

        specialization = (
            "🤖 **Recommended specialization:** AI / Machine Learning\n\n"
            "Focus on Python → Machine Learning → Deep Learning → "
            "NLP/Computer Vision → Generative AI → RAG/LLMs."
        )

    elif "data" in goal_lower:

        specialization = (
            "📊 **Recommended specialization:** Data\n\n"
            "Focus on Python → SQL → Statistics → Pandas/NumPy → "
            "Data Visualization → Machine Learning."
        )

    elif "software" in goal_lower or "developer" in goal_lower:

        specialization = (
            "💻 **Recommended specialization:** Software Development\n\n"
            "Focus on programming → DSA → OOP → Git/GitHub → "
            "backend/frontend → projects."
        )

    else:

        specialization = (
            "🎯 **Recommended specialization:** Build strong programming "
            "fundamentals and specialize according to the strongest market signals."
        )

    # --------------------------------------------------------
    # Report
    # --------------------------------------------------------

    report = f"""
## 🗺️ CareerPilot Personalized Roadmap

### 🎯 Career Target

**{goal}**

---

### 💻 Current Skill Profile

{", ".join(sorted(user_skills)) if user_skills else "No recognised skills detected."}

---

### 📚 Market-Based Skill Gaps

{", ".join(gaps) if gaps else "No major gaps detected from the current market sample."}

---

### 🚀 Your Roadmap

{chr(10).join(roadmap)}

---

### 🧠 CareerPilot Recommendation

{specialization}

---

### 🔄 Continuous Improvement

CareerPilot should continuously repeat:

**Search → Analyze → Identify Gaps → Learn → Build → Apply → Interview → Update Profile → Search Again**

> ⚠️ This roadmap is based on the current opportunity sample and should be treated as guidance rather than a guarantee of employment.
"""

    roadmap_table = pd.DataFrame({
        "Stage": list(range(1, len(roadmap) + 1)),
        "Action": [
            re.sub(r"\*\*", "", item.split("\n")[0])
            for item in roadmap
        ]
    })

    return report, roadmap_table


print("✅ Personalized Career Roadmap created!")

✅ Personalized Career Roadmap created!

In [63]:
# ============================================================
# 🧪 TEST CAREER ROADMAP
# ============================================================

goal = "AI/ML internships"

current_skills = """
Python, Java, AI, Machine Learning, NLP
"""

market_table = None

if "CAREER_MISSION_CACHE" in globals():

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if not opportunities.empty:

        _, market_table = career_market_intelligence(
            opportunities
        )

roadmap_report, roadmap_table = career_roadmap(
    goal,
    current_skills,
    market_table
)

print(roadmap_report)

print("\n📊 ROADMAP TABLE")
display(roadmap_table)

## 🗺️ CareerPilot Personalized Roadmap

### 🎯 Career Target

**AI/ML internships**

---

### 💻 Current Skill Profile

Artificial Intelligence, Java, Machine Learning, NLP, Python

---

### 📚 Market-Based Skill Gaps

No major gaps detected from the current market sample.

---

### 🚀 Your Roadmap

1️⃣ **Strengthen your current foundation**
Practice Python, programming fundamentals and problem solving.
2️⃣ **Learn Machine Learning**
Understand the fundamentals and build small practical examples.
3️⃣ **Learn Generative AI**
Understand the fundamentals and build small practical examples.
4️⃣ **Learn RAG**
Understand the fundamentals and build small practical examples.
5️⃣ **Learn SQL**
Understand the fundamentals and build small practical examples.
6️⃣ **Build 2–3 portfolio projects**
Create projects that demonstrate the skills demanded by the market.
7️⃣ **Publish your projects**
Upload clean projects to GitHub with README files, screenshots and setup instructions.
8️⃣ **Prepare your resume**
Highlight measurable project results and relevant technical skills.
9️⃣ **Prepare for interviews**
Practice technical questions, project explanations and behavioral questions.
10️⃣ **Apply consistently**
Track applications and prioritize opportunities with the highest CareerPilot scores.

---

### 🧠 CareerPilot Recommendation

🤖 **Recommended specialization:** AI / Machine Learning

Focus on Python → Machine Learning → Deep Learning → NLP/Computer Vision → Generative AI → RAG/LLMs.

---

### 🔄 Continuous Improvement

CareerPilot should continuously repeat:

**Search → Analyze → Identify Gaps → Learn → Build → Apply → Interview → Update Profile → Search Again**

> ⚠️ This roadmap is based on the current opportunity sample and should be treated as guidance rather than a guarantee of employment.


📊 ROADMAP TABLE

   Stage                                  Action
0      1  1️⃣ Strengthen your current foundation
1      2              2️⃣ Learn Machine Learning
2      3                 3️⃣ Learn Generative AI
3      4                           4️⃣ Learn RAG
4      5                           5️⃣ Learn SQL
5      6        6️⃣ Build 2–3 portfolio projects
6      7               7️⃣ Publish your projects
7      8                 8️⃣ Prepare your resume
8      9              9️⃣ Prepare for interviews
9     10                 10️⃣ Apply consistently

In [64]:
# ============================================================
# 📋 CAREERPILOT X — APPLICATION TRACKER
# ============================================================

import pandas as pd
from datetime import datetime

APPLICATION_TRACKER = []


def add_application(
    company,
    opportunity,
    link="",
    status="Saved",
    score=0,
    notes=""
):

    application = {
        "Company": str(company).strip(),
        "Opportunity": str(opportunity).strip(),
        "Link": str(link).strip(),
        "Date": datetime.now().strftime("%Y-%m-%d"),
        "Status": str(status).strip(),
        "CareerPilot Score": float(score or 0),
        "Notes": str(notes).strip()
    }

    APPLICATION_TRACKER.append(application)

    return get_application_tracker()


def get_application_tracker():

    if not APPLICATION_TRACKER:

        empty_df = pd.DataFrame(columns=[
            "Company",
            "Opportunity",
            "Link",
            "Date",
            "Status",
            "CareerPilot Score",
            "Notes"
        ])

        summary = """
## 📋 Application Tracker

No applications tracked yet.

Add your first opportunity to begin tracking your career journey.
"""

        return summary, empty_df

    df = pd.DataFrame(APPLICATION_TRACKER)

    # --------------------------------------------------------
    # Status counts
    # --------------------------------------------------------

    saved = int((df["Status"] == "Saved").sum())
    applied = int((df["Status"] == "Applied").sum())
    assessment = int((df["Status"] == "Assessment").sum())
    interview = int((df["Status"] == "Interview").sum())
    offer = int((df["Status"] == "Offer").sum())
    rejected = int((df["Status"] == "Rejected").sum())

    # --------------------------------------------------------
    # Summary
    # --------------------------------------------------------

    summary = f"""
## 📋 CareerPilot Application Tracker

### 📊 Application Overview

| Status | Count |
|---|---:|
| 🔖 Saved | **{saved}** |
| 📤 Applied | **{applied}** |
| 📝 Assessment | **{assessment}** |
| 🎤 Interview | **{interview}** |
| 🏆 Offer | **{offer}** |
| ❌ Rejected | **{rejected}** |

---

### 🎯 Total Opportunities

**{len(df)}**

### 🏆 Offers

**{offer}**

### 🎤 Active Interviews

**{interview}**

---

### 🔄 CareerPilot Workflow

**Discover → Analyze → Save → Apply → Interview → Track → Improve**
"""

    return summary, df


def clear_application_tracker():

    APPLICATION_TRACKER.clear()

    return get_application_tracker()


print("✅ Application Tracker created!")

✅ Application Tracker created!

In [65]:
# ============================================================
# 🧪 TEST APPLICATION TRACKER
# ============================================================

APPLICATION_TRACKER.clear()

add_application(
    company="Example AI Company",
    opportunity="AI/ML Intern",
    link="https://example.com/job",
    status="Saved",
    score=82,
    notes="Strong match for Python + ML"
)

add_application(
    company="Example Tech",
    opportunity="Machine Learning Intern",
    link="https://example.com/ml",
    status="Applied",
    score=76,
    notes="Application submitted"
)

add_application(
    company="Example Startup",
    opportunity="AI Intern",
    link="https://example.com/ai",
    status="Interview",
    score=88,
    notes="Prepare ML and NLP questions"
)

tracker_summary, tracker_table = get_application_tracker()

print(tracker_summary)

print("\n📊 TRACKER TABLE")
display(tracker_table)

## 📋 CareerPilot Application Tracker

### 📊 Application Overview

| Status | Count |
|---|---:|
| 🔖 Saved | **1** |
| 📤 Applied | **1** |
| 📝 Assessment | **0** |
| 🎤 Interview | **1** |
| 🏆 Offer | **0** |
| ❌ Rejected | **0** |

---

### 🎯 Total Opportunities

**3**

### 🏆 Offers

**0**

### 🎤 Active Interviews

**1**

---

### 🔄 CareerPilot Workflow

**Discover → Analyze → Save → Apply → Interview → Track → Improve**


📊 TRACKER TABLE

,Company,Opportunity,Link,Date,Status,CareerPilot Score,Notes
0,Example AI Company,AI/ML Intern,https://example.com/job,2026-10-04,Saved,82.0,Strong match for Python + ML
1,Example Tech,Machine Learning Intern,https://example.com/ml,2026-10-04,Applied,76.0,Application submitted
2,Example Startup,AI Intern,https://example.com/ai,2026-10-04,Interview,88.0,Prepare ML and NLP questions

In [66]:
# ============================================================
# 👤 CAREERPILOT X — CAREER DIGITAL TWIN
# ============================================================

def career_digital_twin(
    career_goal,
    education,
    skills,
    opportunities=None,
    market_table=None
):

    goal = str(career_goal).strip()
    education = str(education).strip()
    skills_text = str(skills).strip()

    # --------------------------------------------------------
    # Detect current skills
    # --------------------------------------------------------

    detected_skills = detect_opportunity_skills(skills_text)

    # Also support manually entered common skills
    if not detected_skills:
        detected_skills = [
            x.strip()
            for x in skills_text.split(",")
            if x.strip()
        ]

    # --------------------------------------------------------
    # Opportunity statistics
    # --------------------------------------------------------

    total_opportunities = 0
    average_match = 0
    average_relevance = 0

    if isinstance(opportunities, pd.DataFrame):

        if not opportunities.empty:

            total_opportunities = len(opportunities)

            if "Match %" in opportunities.columns:
                average_match = round(
                    pd.to_numeric(
                        opportunities["Match %"],
                        errors="coerce"
                    ).fillna(0).mean(),
                    1
                )

            if "Relevance %" in opportunities.columns:
                average_relevance = round(
                    pd.to_numeric(
                        opportunities["Relevance %"],
                        errors="coerce"
                    ).fillna(0).mean(),
                    1
                )

    # --------------------------------------------------------
    # Market skills
    # --------------------------------------------------------

    market_skills = []

    if isinstance(market_table, pd.DataFrame):

        if not market_table.empty and "Skill" in market_table.columns:

            market_skills = market_table["Skill"].astype(str).tolist()

    # --------------------------------------------------------
    # Skill gaps
    # --------------------------------------------------------

    normalized_user_skills = {
        x.lower()
        for x in detected_skills
    }

    skill_gaps = [
        skill
        for skill in market_skills
        if skill.lower() not in normalized_user_skills
    ]

    skill_gaps = list(dict.fromkeys(skill_gaps))

    # --------------------------------------------------------
    # Career readiness score
    # --------------------------------------------------------

    skill_score = min(
        100,
        len(detected_skills) * 10
    )

    opportunity_score = min(
        100,
        total_opportunities * 10
    )

    readiness_score = round(
        skill_score * 0.40 +
        average_match * 0.35 +
        opportunity_score * 0.25,
        1
    )

    if readiness_score >= 80:
        readiness = "🔥 Highly Ready"

    elif readiness_score >= 60:
        readiness = "🟢 Good Progress"

    elif readiness_score >= 40:
        readiness = "🟡 Developing"

    else:
        readiness = "🔴 Early Stage"

    # --------------------------------------------------------
    # Recommended focus
    # --------------------------------------------------------

    if skill_gaps:

        focus = skill_gaps[:5]

    else:

        focus = [
            "Deep Learning",
            "Generative AI",
            "RAG",
            "LLMs"
        ]

    # --------------------------------------------------------
    # Digital Twin report
    # --------------------------------------------------------

    report = f"""
## 👤 CareerPilot Digital Twin

### 🎯 Career Goal

**{goal}**

### 🎓 Education

**{education}**

---

### 💻 Current Skill Profile

{", ".join(sorted(detected_skills)) if detected_skills else "No recognised skills detected."}

---

### 📊 Career Metrics

| Metric | Value |
|---|---:|
| Career Readiness | **{readiness_score}%** |
| Profile Match | **{average_match}%** |
| Average Relevance | **{average_relevance}%** |
| Opportunities Analyzed | **{total_opportunities}** |

### 🚦 Readiness Status

**{readiness}**

---

### 📚 Recommended Skill Focus

{chr(10).join(
    [f"- 📚 **{skill}**" for skill in focus]
)}

---

### 🧠 Digital Twin Insight

CareerPilot currently understands your profile as:

**{education} → {goal}**

with **{len(detected_skills)} recognised technical skills** and
**{len(skill_gaps)} potential market skill gaps**.

---

### 🔄 Dynamic Profile Loop

**Profile → Search → Analyze → Learn → Apply → Interview → Update Profile**

Your Digital Twin can be updated whenever your skills, projects,
applications or career goals change.

> ⚠️ Career readiness is an internal CareerPilot estimate, not a prediction of employment.
"""

    # --------------------------------------------------------
    # Digital Twin table
    # --------------------------------------------------------

    twin_table = pd.DataFrame([{
        "Career Goal": goal,
        "Education": education,
        "Readiness %": readiness_score,
        "Profile Match %": average_match,
        "Average Relevance %": average_relevance,
        "Skills": ", ".join(sorted(detected_skills)),
        "Skill Gaps": ", ".join(skill_gaps),
        "Opportunities": total_opportunities,
        "Status": readiness
    }])

    return report, twin_table


print("✅ Career Digital Twin created!")

✅ Career Digital Twin created!

In [67]:
# ============================================================
# 🧪 TEST CAREER DIGITAL TWIN
# ============================================================

goal = "AI/ML internships"

education = "BTech CSE-AIML"

skills = """
Python, Java, AI, Machine Learning, NLP
"""

opportunities = pd.DataFrame()

market_table = pd.DataFrame()

if "CAREER_MISSION_CACHE" in globals():

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if not opportunities.empty:

        _, market_table = career_market_intelligence(
            opportunities
        )

twin_report, twin_table = career_digital_twin(
    goal,
    education,
    skills,
    opportunities,
    market_table
)

print(twin_report)

print("\n📊 DIGITAL TWIN TABLE")
display(twin_table)

## 👤 CareerPilot Digital Twin

### 🎯 Career Goal

**AI/ML internships**

### 🎓 Education

**BTech CSE-AIML**

---

### 💻 Current Skill Profile

Artificial Intelligence, Java, Machine Learning, NLP, Python

---

### 📊 Career Metrics

| Metric | Value |
|---|---:|
| Career Readiness | **51.1%** |
| Profile Match | **53.2%** |
| Average Relevance | **63.6%** |
| Opportunities Analyzed | **5** |

### 🚦 Readiness Status

**🟡 Developing**

---

### 📚 Recommended Skill Focus

- 📚 **Deep Learning**
- 📚 **Generative AI**
- 📚 **RAG**
- 📚 **LLMs**

---

### 🧠 Digital Twin Insight

CareerPilot currently understands your profile as:

**BTech CSE-AIML → AI/ML internships**

with **5 recognised technical skills** and
**0 potential market skill gaps**.

---

### 🔄 Dynamic Profile Loop

**Profile → Search → Analyze → Learn → Apply → Interview → Update Profile**

Your Digital Twin can be updated whenever your skills, projects,
applications or career goals change.

> ⚠️ Career readiness is an internal CareerPilot estimate, not a prediction of employment.


📊 DIGITAL TWIN TABLE

,Career Goal,Education,Readiness %,Profile Match %,Average Relevance %,Skills,Skill Gaps,Opportunities,Status
0,AI/ML internships,BTech CSE-AIML,51.1,53.2,63.6,"Artificial Intelligence, Java, Machine Learnin...",,5,🟡 Developing

In [68]:
# ============================================================
# 🔄 CAREERPILOT X — CLOSED-LOOP CAREER AGENT
# ============================================================

def career_closed_loop(
    career_goal,
    education,
    current_skills,
    opportunities=None,
    market_table=None,
    applications=None
):

    goal = str(career_goal).strip()
    education = str(education).strip()
    skills = str(current_skills).strip()

    # --------------------------------------------------------
    # Opportunity analysis
    # --------------------------------------------------------

    total_opportunities = 0
    average_match = 0
    average_relevance = 0

    if isinstance(opportunities, pd.DataFrame):

        if not opportunities.empty:

            total_opportunities = len(opportunities)

            if "Match %" in opportunities.columns:

                average_match = round(
                    pd.to_numeric(
                        opportunities["Match %"],
                        errors="coerce"
                    ).fillna(0).mean(),
                    1
                )

            if "Relevance %" in opportunities.columns:

                average_relevance = round(
                    pd.to_numeric(
                        opportunities["Relevance %"],
                        errors="coerce"
                    ).fillna(0).mean(),
                    1
                )

    # --------------------------------------------------------
    # Market skills
    # --------------------------------------------------------

    market_skills = []

    if isinstance(market_table, pd.DataFrame):

        if not market_table.empty and "Skill" in market_table.columns:

            market_skills = market_table["Skill"].astype(str).tolist()

    # --------------------------------------------------------
    # User skills
    # --------------------------------------------------------

    detected_skills = detect_opportunity_skills(skills)

    # --------------------------------------------------------
    # Skill gaps
    # --------------------------------------------------------

    user_skill_lower = {
        x.lower()
        for x in detected_skills
    }

    skill_gaps = [
        skill
        for skill in market_skills
        if skill.lower() not in user_skill_lower
    ]

    skill_gaps = list(dict.fromkeys(skill_gaps))

    # --------------------------------------------------------
    # Application statistics
    # --------------------------------------------------------

    total_applications = 0
    applied = 0
    interviews = 0
    offers = 0

    if applications is None:

        if "APPLICATION_TRACKER" in globals():
            applications = APPLICATION_TRACKER

    if applications:

        try:

            application_df = pd.DataFrame(applications)

            total_applications = len(application_df)

            if "Status" in application_df.columns:

                applied = int(
                    (application_df["Status"] == "Applied").sum()
                )

                interviews = int(
                    (application_df["Status"] == "Interview").sum()
                )

                offers = int(
                    (application_df["Status"] == "Offer").sum()
                )

        except:

            pass

    # --------------------------------------------------------
    # Career readiness
    # --------------------------------------------------------

    skill_score = min(
        100,
        len(detected_skills) * 10
    )

    opportunity_score = min(
        100,
        total_opportunities * 10
    )

    application_score = min(
        100,
        total_applications * 20
    )

    readiness = round(
        skill_score * 0.35 +
        average_match * 0.30 +
        opportunity_score * 0.15 +
        application_score * 0.20,
        1
    )

    # --------------------------------------------------------
    # Current stage
    # --------------------------------------------------------

    if offers > 0:

        current_stage = "🏆 Offer"

    elif interviews > 0:

        current_stage = "🎤 Interview"

    elif applied > 0:

        current_stage = "📤 Application"

    elif total_opportunities > 0:

        current_stage = "🎯 Opportunity Discovery"

    else:

        current_stage = "🔎 Discovery"

    # --------------------------------------------------------
    # Next best action
    # --------------------------------------------------------

    if skill_gaps:

        next_action = (
            f"📚 Strengthen **{skill_gaps[0]}** "
            "before applying to more opportunities."
        )

    elif total_applications == 0 and total_opportunities > 0:

        next_action = (
            "📋 Select the highest-ranked opportunities "
            "and start applying."
        )

    elif interviews == 0 and applied > 0:

        next_action = (
            "🎤 Prepare for technical interviews "
            "using CareerPilot Interview Simulator."
        )

    elif interviews > 0:

        next_action = (
            "🎯 Focus on interview preparation and "
            "project explanations."
        )

    else:

        next_action = (
            "🔎 Continue searching for stronger opportunities."
        )

    # --------------------------------------------------------
    # Closed-loop report
    # --------------------------------------------------------

    report = f"""
## 🔄 CareerPilot Closed-Loop Career Agent

### 🎯 Career Target

**{goal}**

### 🎓 Education

**{education}**

---

## 📊 Current Career State

| Metric | Value |
|---|---:|
| Career Readiness | **{readiness}%** |
| Opportunities | **{total_opportunities}** |
| Average Match | **{average_match}%** |
| Average Relevance | **{average_relevance}%** |
| Applications | **{total_applications}** |
| Interviews | **{interviews}** |
| Offers | **{offers}** |

### 🚦 Current Stage

**{current_stage}**

---

## 💻 Current Skills

{", ".join(sorted(detected_skills)) if detected_skills else "No recognised skills detected."}

---

## 📚 Skill Gaps

{", ".join(skill_gaps) if skill_gaps else "No immediate market skill gaps detected."}

---

## 🚀 Next Best Action

### {next_action}

---

## 🧠 CareerPilot Closed Loop

**🔎 Discover**

Find live opportunities using SerpApi.

↓

**🧠 Analyze**

Evaluate relevance, profile match, confidence and skill signals.

↓

**🎯 Match**

Rank opportunities using CareerPilot scoring.

↓

**📚 Improve**

Identify market skills and learning gaps.

↓

**🗺️ Prepare**

Generate a personalized roadmap and interview preparation.

↓

**📋 Apply**

Track applications and progress.

↓

**🎤 Interview**

Practice and evaluate interview answers.

↓

**👤 Update Digital Twin**

Update the career profile using the latest progress.

↓

**🔄 Discover Again**

Search for better opportunities using the improved profile.

---

### 🚀 System Status

**CareerPilot is designed as a continuous career-improvement loop rather than a one-time job search.**

> ⚠️ Readiness and recommendations are CareerPilot estimates based on the available data.
"""

    # --------------------------------------------------------
    # Loop metrics table
    # --------------------------------------------------------

    loop_table = pd.DataFrame([{
        "Career Goal": goal,
        "Current Stage": current_stage,
        "Readiness %": readiness,
        "Opportunities": total_opportunities,
        "Applications": total_applications,
        "Interviews": interviews,
        "Offers": offers,
        "Skill Gaps": ", ".join(skill_gaps),
        "Next Action": next_action
    }])

    return report, loop_table


print("✅ Closed-Loop Career Agent created!")

✅ Closed-Loop Career Agent created!

In [69]:
# ============================================================
# 🧪 TEST CLOSED-LOOP CAREER AGENT
# ============================================================

goal = "AI/ML internships"

education = "BTech CSE-AIML"

skills = """
Python, Java, AI, Machine Learning, NLP
"""

opportunities = pd.DataFrame()
market_table = pd.DataFrame()

if "CAREER_MISSION_CACHE" in globals():

    opportunities = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if not opportunities.empty:

        _, market_table = career_market_intelligence(
            opportunities
        )

closed_report, closed_table = career_closed_loop(
    goal,
    education,
    skills,
    opportunities,
    market_table,
    APPLICATION_TRACKER
)

print(closed_report)

print("\n📊 CLOSED-LOOP STATUS")
display(closed_table)

## 🔄 CareerPilot Closed-Loop Career Agent

### 🎯 Career Target

**AI/ML internships**

### 🎓 Education

**BTech CSE-AIML**

---

## 📊 Current Career State

| Metric | Value |
|---|---:|
| Career Readiness | **53.0%** |
| Opportunities | **5** |
| Average Match | **53.2%** |
| Average Relevance | **63.6%** |
| Applications | **3** |
| Interviews | **1** |
| Offers | **0** |

### 🚦 Current Stage

**🎤 Interview**

---

## 💻 Current Skills

Artificial Intelligence, Java, Machine Learning, NLP, Python

---

## 📚 Skill Gaps

No immediate market skill gaps detected.

---

## 🚀 Next Best Action

### 🎯 Focus on interview preparation and project explanations.

---

## 🧠 CareerPilot Closed Loop

**🔎 Discover**

Find live opportunities using SerpApi.

↓

**🧠 Analyze**

Evaluate relevance, profile match, confidence and skill signals.

↓

**🎯 Match**

Rank opportunities using CareerPilot scoring.

↓

**📚 Improve**

Identify market skills and learning gaps.

↓

**🗺️ Prepare**

Generate a personalized roadmap and interview preparation.

↓

**📋 Apply**

Track applications and progress.

↓

**🎤 Interview**

Practice and evaluate interview answers.

↓

**👤 Update Digital Twin**

Update the career profile using the latest progress.

↓

**🔄 Discover Again**

Search for better opportunities using the improved profile.

---

### 🚀 System Status

**CareerPilot is designed as a continuous career-improvement loop rather than a one-time job search.**

> ⚠️ Readiness and recommendations are CareerPilot estimates based on the available data.


📊 CLOSED-LOOP STATUS

,Career Goal,Current Stage,Readiness %,Opportunities,Applications,Interviews,Offers,Skill Gaps,Next Action
0,AI/ML internships,🎤 Interview,53.0,5,3,1,0,,🎯 Focus on interview preparation and project e...

In [72]:
# ============================================================
# 🔧 FIX WHAT-IF CAREER LAB
# ============================================================

def dashboard_what_if(
    goal,
    current_skills,
    additional_skills,
    target_role
):
    try:
        result = what_if_career_lab(
            goal,
            current_skills,
            additional_skills,
            target_role
        )

        # What-If returns: (report, table)
        if isinstance(result, tuple) and len(result) == 2:
            return result[0], result[1]

        # Safety fallback
        return str(result), pd.DataFrame()

    except Exception as e:
        return (
            f"❌ What-If Career Lab Error\n\n`{e}`",
            pd.DataFrame()
        )


print("✅ What-If Career Lab fixed!")

✅ What-If Career Lab fixed!

In [77]:
%%writefile app.py

print("CareerPilot-X Streamlit app")

Writing app.py

In [76]:
# ============================================================
# 🚀 CAREERPILOT X — FINAL ALL-IN-ONE DASHBOARD
# ============================================================

import gradio as gr
import pandas as pd
import traceback

# ============================================================
# SHARED CACHE
# ============================================================

if "CAREER_MISSION_CACHE" not in globals():
    CAREER_MISSION_CACHE = {}

CAREER_MISSION_CACHE["opportunities"] = pd.DataFrame()

if "APPLICATION_TRACKER" not in globals():
    APPLICATION_TRACKER = []


# ============================================================
# HELPER — GET LIVE OPPORTUNITIES
# ============================================================

def get_cached_opportunities():
    opp = CAREER_MISSION_CACHE.get(
        "opportunities",
        pd.DataFrame()
    )

    if isinstance(opp, pd.DataFrame):
        return opp

    try:
        return pd.DataFrame(opp)
    except:
        return pd.DataFrame()


# ============================================================
# 🎯 CAREER MISSION
# ============================================================

def dashboard_career_mission(
    goal,
    education,
    skills,
    location,
    experience
):

    try:

        result = run_career_mission(
            goal,
            education,
            skills,
            location,
            experience
        )

        if isinstance(result, tuple) and len(result) == 6:

            opportunities = result[0]

            if isinstance(opportunities, pd.DataFrame):
                CAREER_MISSION_CACHE["opportunities"] = opportunities.copy()

            CAREER_MISSION_CACHE["profile"] = {
                "goal": goal,
                "education": education,
                "skills": skills,
                "location": location,
                "experience": experience
            }

            return result

        return (
            pd.DataFrame(),
            "❌ Career Mission returned an unexpected result.",
            "",
            "",
            "",
            ""
        )

    except Exception as e:

        traceback.print_exc()

        return (
            pd.DataFrame(),
            f"❌ Career Mission Error: `{e}`",
            "",
            "",
            "",
            ""
        )


# ============================================================
# 📄 RESUME INTELLIGENCE
# ============================================================

def dashboard_resume(resume_file):

    try:

        opportunities = get_cached_opportunities()

        return resume_intelligence(
            resume_file,
            opportunities
        )

    except Exception as e:

        return (
            f"❌ Resume Error: `{e}`",
            [],
            0,
            pd.DataFrame(),
            "Please upload a text-based PDF or TXT resume."
        )


# ============================================================
# 🏆 OPPORTUNITY INTELLIGENCE
# ============================================================

def dashboard_opportunity(user_skills):

    try:

        opportunities = get_cached_opportunities()

        if opportunities.empty:

            return (
                "⚠️ Please run **🎯 Career Mission** first.",
                pd.DataFrame()
            )

        return opportunity_intelligence(
            opportunities,
            user_skills
        )

    except Exception as e:

        return (
            f"❌ Opportunity Intelligence Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 🤖 INTERVIEW SIMULATOR
# ============================================================

def dashboard_generate_interview(
    career_goal,
    skills,
    number_of_questions
):

    try:

        return interview_session(
            career_goal,
            skills,
            int(number_of_questions)
        )

    except Exception as e:

        return f"❌ Interview Error: `{e}`"


def dashboard_evaluate_interview(
    question,
    answer
):

    try:

        return evaluate_interview_answer(
            question,
            answer
        )

    except Exception as e:

        return (
            f"❌ Evaluation Error: `{e}`",
            0,
            str(e)
        )


# ============================================================
# 🔮 WHAT-IF CAREER LAB — FIXED
# ============================================================

def dashboard_what_if(
    goal,
    current_skills,
    additional_skills,
    target_role
):

    try:

        result = what_if_career_lab(
            goal,
            current_skills,
            additional_skills,
            target_role
        )

        # Your function returns:
        # (report, table)

        if isinstance(result, tuple):

            if len(result) >= 2:

                report = result[0]
                table = result[1]

                if not isinstance(table, pd.DataFrame):

                    try:
                        table = pd.DataFrame(table)
                    except:
                        table = pd.DataFrame()

                return str(report), table

            if len(result) == 1:
                return str(result[0]), pd.DataFrame()

        return str(result), pd.DataFrame()

    except Exception as e:

        traceback.print_exc()

        return (
            f"❌ What-If Career Lab Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 🧬 OPPORTUNITY DNA
# ============================================================

def dashboard_dna(index):

    try:

        opportunities = get_cached_opportunities()

        if opportunities.empty:

            return (
                "⚠️ Please run **🎯 Career Mission** first.",
                pd.DataFrame()
            )

        index = int(index)

        if index < 0:
            index = 0

        if index >= len(opportunities):
            index = 0

        return opportunity_dna(
            opportunities,
            index
        )

    except Exception as e:

        return (
            f"❌ Opportunity DNA Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 📈 MARKET INTELLIGENCE
# ============================================================

def dashboard_market():

    try:

        opportunities = get_cached_opportunities()

        if opportunities.empty:

            return (
                "⚠️ Please run **🎯 Career Mission** first.",
                pd.DataFrame()
            )

        result = career_market_intelligence(
            opportunities
        )

        if isinstance(result, tuple) and len(result) == 2:

            CAREER_MISSION_CACHE["market_table"] = result[1]

        return result

    except Exception as e:

        return (
            f"❌ Market Intelligence Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 🗺️ CAREER ROADMAP
# ============================================================

def dashboard_roadmap(
    goal,
    skills
):

    try:

        opportunities = get_cached_opportunities()

        if opportunities.empty:

            return (
                "⚠️ Please run **🎯 Career Mission** first.",
                pd.DataFrame()
            )

        market_result = career_market_intelligence(
            opportunities
        )

        market_table = (
            market_result[1]
            if isinstance(market_result, tuple)
            and len(market_result) >= 2
            else pd.DataFrame()
        )

        return career_roadmap(
            goal,
            skills,
            market_table
        )

    except Exception as e:

        return (
            f"❌ Roadmap Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 📋 APPLICATION TRACKER
# ============================================================

def dashboard_add_application(
    company,
    opportunity,
    link,
    status,
    score,
    notes
):

    try:

        return add_application(
            company,
            opportunity,
            link,
            status,
            score,
            notes
        )[1]

    except Exception as e:

        return pd.DataFrame([
            {
                "Error": str(e)
            }
        ])


def dashboard_refresh_tracker():

    try:

        result = get_application_tracker()

        if isinstance(result, tuple):
            return result[1]

        return result

    except Exception as e:

        return pd.DataFrame([
            {
                "Error": str(e)
            }
        ])


def dashboard_clear_tracker():

    try:

        result = clear_application_tracker()

        if isinstance(result, tuple):
            return result[1]

        return result

    except Exception as e:

        return pd.DataFrame([
            {
                "Error": str(e)
            }
        ])


# ============================================================
# 👤 DIGITAL TWIN
# ============================================================

def dashboard_digital_twin(
    goal,
    education,
    skills
):

    try:

        opportunities = get_cached_opportunities()

        market_table = CAREER_MISSION_CACHE.get(
            "market_table",
            pd.DataFrame()
        )

        return career_digital_twin(
            goal,
            education,
            skills,
            opportunities,
            market_table
        )

    except Exception as e:

        return (
            f"❌ Digital Twin Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 🔄 CLOSED LOOP
# ============================================================

def dashboard_closed_loop(
    goal,
    education,
    skills
):

    try:

        opportunities = get_cached_opportunities()

        market_table = CAREER_MISSION_CACHE.get(
            "market_table",
            pd.DataFrame()
        )

        return career_closed_loop(
            goal,
            education,
            skills,
            opportunities,
            market_table,
            APPLICATION_TRACKER
        )

    except Exception as e:

        return (
            f"❌ Closed Loop Error: `{e}`",
            pd.DataFrame()
        )


# ============================================================
# 🚀 BUILD COMPLETE DASHBOARD
# ============================================================

with gr.Blocks(
    title="CareerPilot X",
    theme=gr.themes.Soft()
) as demo:

    # ========================================================
    # HEADER
    # ========================================================

    gr.Markdown("""
# 🚀 CareerPilot X

### Autonomous Career Intelligence Platform

**Live Web Intelligence • Career Matching • Skill Intelligence • Resume Analysis • Interview Preparation • Career Planning**

**Built for the SerpApi India Hackathon 2026 🇮🇳**

---

### 🔄 Discover → Analyze → Match → Improve → Prepare → Apply → Interview → Update → Discover Again

> Run **Career Mission first** to collect live opportunities. The other intelligence features use those results.
""")

    # ========================================================
    # 🎯 1. CAREER MISSION
    # ========================================================

    with gr.Tab("🎯 Career Mission"):

        gr.Markdown("""
## 🎯 Career Mission

Tell CareerPilot what career opportunity you are looking for.

CareerPilot searches the live web using SerpApi and analyzes the results.
""")

        with gr.Row():

            mission_goal = gr.Textbox(
                label="🎯 Career Goal",
                value="AI/ML internships"
            )

            mission_education = gr.Textbox(
                label="🎓 Education",
                value="BTech CSE-AIML"
            )

        with gr.Row():

            mission_skills = gr.Textbox(
                label="💻 Current Skills",
                value="Python, Java, AI, Machine Learning, NLP"
            )

            mission_location = gr.Textbox(
                label="📍 Location",
                value="India"
            )

        mission_experience = gr.Textbox(
            label="👩‍💻 Experience",
            value="Student"
        )

        mission_button = gr.Button(
            "🚀 Start Career Mission",
            variant="primary"
        )

        mission_opportunities = gr.Dataframe(
            label="🔎 Live Opportunities",
            interactive=False
        )

        mission_summary = gr.Markdown()

        mission_skills_output = gr.Markdown()

        mission_market_output = gr.Markdown()

        mission_roadmap_output = gr.Markdown()

        mission_log = gr.Markdown()

        mission_button.click(
            dashboard_career_mission,
            inputs=[
                mission_goal,
                mission_education,
                mission_skills,
                mission_location,
                mission_experience
            ],
            outputs=[
                mission_opportunities,
                mission_summary,
                mission_skills_output,
                mission_market_output,
                mission_roadmap_output,
                mission_log
            ]
        )

    # ========================================================
    # 📄 2. RESUME INTELLIGENCE
    # ========================================================

    with gr.Tab("📄 Resume Intelligence"):

        gr.Markdown("""
## 📄 Resume Intelligence

Upload your resume and compare it against the live opportunities discovered by CareerPilot.
""")

        resume_file = gr.File(
            label="📄 Upload Resume",
            file_types=[".pdf", ".txt"],
            type="filepath"
        )

        resume_button = gr.Button(
            "🔍 Analyze Resume",
            variant="primary"
        )

        resume_summary = gr.Markdown()

        resume_skills_output = gr.JSON(
            label="💻 Detected Skills"
        )

        resume_score = gr.Number(
            label="🎯 Overall Resume Match %"
        )

        resume_table = gr.Dataframe(
            label="📊 Opportunity Resume Match",
            interactive=False
        )

        resume_recommendations = gr.Markdown()

        resume_button.click(
            dashboard_resume,
            inputs=resume_file,
            outputs=[
                resume_summary,
                resume_skills_output,
                resume_score,
                resume_table,
                resume_recommendations
            ]
        )

    # ========================================================
    # 🏆 3. OPPORTUNITY INTELLIGENCE
    # ========================================================

    with gr.Tab("🏆 Opportunity Intelligence"):

        gr.Markdown("""
## 🏆 Opportunity Intelligence

Rank opportunities using:

**Relevance + Profile Match + Skill Alignment**
""")

        opportunity_skills_input = gr.Textbox(
            label="💻 Your Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        opportunity_button = gr.Button(
            "🏆 Analyze Opportunities",
            variant="primary"
        )

        opportunity_report = gr.Markdown()

        opportunity_table = gr.Dataframe(
            label="🏆 Ranked Opportunities",
            interactive=False
        )

        opportunity_button.click(
            dashboard_opportunity,
            inputs=opportunity_skills_input,
            outputs=[
                opportunity_report,
                opportunity_table
            ]
        )

    # ========================================================
    # 🤖 4. INTERVIEW SIMULATOR
    # ========================================================

    with gr.Tab("🤖 Interview Simulator"):

        gr.Markdown("""
## 🤖 Interview Simulator

Generate questions based on your target career and skills,
then practice and evaluate your answers.
""")

        interview_goal_input = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        interview_skills_input = gr.Textbox(
            label="💻 Skills",
            value="Python, Machine Learning, AI, NLP"
        )

        interview_question_count = gr.Slider(
            minimum=1,
            maximum=10,
            value=5,
            step=1,
            label="Number of Questions"
        )

        generate_interview_button = gr.Button(
            "🎤 Generate Interview Questions",
            variant="primary"
        )

        interview_questions_output = gr.Markdown()

        generate_interview_button.click(
            dashboard_generate_interview,
            inputs=[
                interview_goal_input,
                interview_skills_input,
                interview_question_count
            ],
            outputs=interview_questions_output
        )

        gr.Markdown("---")

        gr.Markdown("### 📝 Practice Your Answer")

        interview_question_input = gr.Textbox(
            label="Question"
        )

        interview_answer_input = gr.Textbox(
            label="Your Answer",
            lines=6,
            placeholder="Type your answer here..."
        )

        evaluate_interview_button = gr.Button(
            "🧠 Evaluate My Answer",
            variant="primary"
        )

        interview_evaluation = gr.Markdown()

        interview_score = gr.Number(
            label="⭐ Interview Score"
        )

        interview_feedback = gr.Markdown()

        evaluate_interview_button.click(
            dashboard_evaluate_interview,
            inputs=[
                interview_question_input,
                interview_answer_input
            ],
            outputs=[
                interview_evaluation,
                interview_score,
                interview_feedback
            ]
        )

    # ========================================================
    # 🔮 5. WHAT-IF CAREER LAB
    # ========================================================

    with gr.Tab("🔮 What-If Career Lab"):

        gr.Markdown("""
## 🔮 What-If Career Lab

Test how adding new skills can change your career readiness.
""")

        whatif_goal_input = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        whatif_current_input = gr.Textbox(
            label="💻 Current Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        whatif_additional_input = gr.Textbox(
            label="🚀 Additional Skills",
            value="Generative AI, RAG, SQL"
        )

        whatif_role_input = gr.Textbox(
            label="🏆 Target Role",
            value="AI/ML Engineer"
        )

        whatif_button = gr.Button(
            "🔮 Run What-If Simulation",
            variant="primary"
        )

        whatif_report = gr.Markdown(
            label="What-If Analysis"
        )

        whatif_table = gr.Dataframe(
            label="📊 Skill Impact Analysis",
            interactive=False
        )

        # IMPORTANT:
        # TWO outputs because what_if_career_lab returns
        # report + table.

        whatif_button.click(
            dashboard_what_if,
            inputs=[
                whatif_goal_input,
                whatif_current_input,
                whatif_additional_input,
                whatif_role_input
            ],
            outputs=[
                whatif_report,
                whatif_table
            ]
        )

    # ========================================================
    # 🧬 6. OPPORTUNITY DNA
    # ========================================================

    with gr.Tab("🧬 Opportunity DNA"):

        gr.Markdown("""
## 🧬 Opportunity DNA

Deep-analyze a selected opportunity using:

**Relevance + Profile Match + Source Confidence + Skill Signal**
""")

        dna_index = gr.Number(
            label="Opportunity Number",
            value=0,
            precision=0
        )

        dna_button = gr.Button(
            "🧬 Analyze Opportunity DNA",
            variant="primary"
        )

        dna_report = gr.Markdown()

        dna_table = gr.Dataframe(
            label="🧬 Opportunity DNA",
            interactive=False
        )

        dna_button.click(
            dashboard_dna,
            inputs=dna_index,
            outputs=[
                dna_report,
                dna_table
            ]
        )

    # ========================================================
    # 📈 7. MARKET INTELLIGENCE
    # ========================================================

    with gr.Tab("📈 Market Intelligence"):

        gr.Markdown("""
## 📈 Career Market Intelligence

Analyze the skills appearing across your live opportunity sample.
""")

        market_button = gr.Button(
            "📈 Analyze Career Market",
            variant="primary"
        )

        market_report = gr.Markdown()

        market_table_output = gr.Dataframe(
            label="📊 Market Skill Demand",
            interactive=False
        )

        market_button.click(
            dashboard_market,
            outputs=[
                market_report,
                market_table_output
            ]
        )

    # ========================================================
    # 🗺️ 8. CAREER ROADMAP
    # ========================================================

    with gr.Tab("🗺️ Career Roadmap"):

        gr.Markdown("""
## 🗺️ Personalized Career Roadmap

Build a step-by-step plan based on your current profile and market signals.
""")

        roadmap_goal_input = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        roadmap_skills_input = gr.Textbox(
            label="💻 Current Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        roadmap_button = gr.Button(
            "🗺️ Generate Career Roadmap",
            variant="primary"
        )

        roadmap_report = gr.Markdown()

        roadmap_table_output = gr.Dataframe(
            label="🗺️ Roadmap",
            interactive=False
        )

        roadmap_button.click(
            dashboard_roadmap,
            inputs=[
                roadmap_goal_input,
                roadmap_skills_input
            ],
            outputs=[
                roadmap_report,
                roadmap_table_output
            ]
        )

    # ========================================================
    # 📋 9. APPLICATION TRACKER
    # ========================================================

    with gr.Tab("📋 Application Tracker"):

        gr.Markdown("""
## 📋 Application Tracker

Save and track your internship/job applications.
""")

        with gr.Row():

            application_company = gr.Textbox(
                label="🏢 Company"
            )

            application_opportunity = gr.Textbox(
                label="💼 Opportunity"
            )

        with gr.Row():

            application_link = gr.Textbox(
                label="🔗 Application Link"
            )

            application_status = gr.Dropdown(
                choices=[
                    "Saved",
                    "Applied",
                    "Interview",
                    "Rejected",
                    "Offer"
                ],
                value="Saved",
                label="📌 Status"
            )

        application_score = gr.Number(
            label="⭐ CareerPilot Score",
            value=0
        )

        application_notes = gr.Textbox(
            label="📝 Notes"
        )

        add_application_button = gr.Button(
            "➕ Add Application",
            variant="primary"
        )

        tracker_table = gr.Dataframe(
            label="📋 My Applications",
            interactive=False
        )

        add_application_button.click(
            dashboard_add_application,
            inputs=[
                application_company,
                application_opportunity,
                application_link,
                application_status,
                application_score,
                application_notes
            ],
            outputs=tracker_table
        )

        refresh_tracker_button = gr.Button(
            "🔄 Refresh Tracker"
        )

        refresh_tracker_button.click(
            dashboard_refresh_tracker,
            outputs=tracker_table
        )

        clear_tracker_button = gr.Button(
            "🗑️ Clear Tracker"
        )

        clear_tracker_button.click(
            dashboard_clear_tracker,
            outputs=tracker_table
        )

    # ========================================================
    # 👤 10. CAREER DIGITAL TWIN
    # ========================================================

    with gr.Tab("👤 Career Digital Twin"):

        gr.Markdown("""
## 👤 Career Digital Twin

Build a dynamic representation of your career profile,
skills, opportunities and readiness.
""")

        twin_goal_input = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        twin_education_input = gr.Textbox(
            label="🎓 Education",
            value="BTech CSE-AIML"
        )

        twin_skills_input = gr.Textbox(
            label="💻 Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        twin_button = gr.Button(
            "👤 Generate Digital Twin",
            variant="primary"
        )

        twin_report = gr.Markdown()

        twin_table = gr.Dataframe(
            label="👤 Digital Twin Metrics",
            interactive=False
        )

        twin_button.click(
            dashboard_digital_twin,
            inputs=[
                twin_goal_input,
                twin_education_input,
                twin_skills_input
            ],
            outputs=[
                twin_report,
                twin_table
            ]
        )

    # ========================================================
    # 🔄 11. CLOSED LOOP
    # ========================================================

    with gr.Tab("🔄 Closed-Loop Agent"):

        gr.Markdown("""
## 🔄 Closed-Loop Career Agent

CareerPilot connects the complete career journey:

**Discover → Analyze → Match → Improve → Prepare → Apply → Interview → Update → Discover Again**
""")

        loop_goal_input = gr.Textbox(
            label="🎯 Career Goal",
            value="AI/ML internships"
        )

        loop_education_input = gr.Textbox(
            label="🎓 Education",
            value="BTech CSE-AIML"
        )

        loop_skills_input = gr.Textbox(
            label="💻 Current Skills",
            value="Python, Java, AI, Machine Learning, NLP"
        )

        loop_button = gr.Button(
            "🔄 Run Closed-Loop Analysis",
            variant="primary"
        )

        loop_report = gr.Markdown()

        loop_table = gr.Dataframe(
            label="🔄 Career Loop Metrics",
            interactive=False
        )

        loop_button.click(
            dashboard_closed_loop,
            inputs=[
                loop_goal_input,
                loop_education_input,
                loop_skills_input
            ],
            outputs=[
                loop_report,
                loop_table
            ]
        )

    # ========================================================
    # FOOTER
    # ========================================================

    gr.Markdown("""
---

# 🚀 CareerPilot X

### Autonomous Career Intelligence Platform

**Live Web Intelligence • Career Matching • Skill Intelligence • Resume Analysis • Interview Preparation • Career Planning**

**Built for the SerpApi India Hackathon 2026 🇮🇳**

> CareerPilot X transforms live web search data into personalized career decisions, actionable skill recommendations, interview preparation and career planning.

⚠️ **Disclaimer:** CareerPilot's relevance, confidence, risk and skill signals are heuristic estimates. Always verify opportunity details directly with the original source before applying.
""")


# ============================================================
# 🚀 LAUNCH
# ============================================================

print("🚀 CareerPilot X — launching complete dashboard...")

demo.launch(
    share=True,
    debug=True
)

/tmp/ipykernel_1955/3326328709.py:523: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: theme. Please pass these parameters to launch() instead.
  with gr.Blocks(

🚀 CareerPilot X — launching complete dashboard...
Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://20b2b41a82c3e9a534.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7867 <> https://20b2b41a82c3e9a534.gradio.live